(function(g){var window=this;'use strict';var X3=function(a){a.ea("cardstatechange",a.zj()&&a.qo()?1:0)},Y3=function(a,b){var c=g.Ia(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},U$a=function(a){var b=g.Il(a);
a=g.Ll(a);return new g.rl(b.x,b.y,a.width,a.height)},V$a=function(a){return Math.pow(a,3)},W$a=function(a){return 3*a*a-2*a*a*a},a4=function(a){a=g.Oa(a);
delete Z3[a];g.Vc(Z3)&&$3&&$3.stop()},Y$a=function(){$3||($3=new g.eo(function(){X$a()},20));
var a=$3;a.isActive()||a.start()},X$a=function(){var a=g.Ra();
g.Fc(Z3,function(b){Z$a(b,a)});
g.Vc(Z3)||Y$a()},b4=function(a,b,c,d){g.yo.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.u=a;this.T=b;this.duration=c;this.I=d;this.coords=[];this.progress=this.J=0;this.D=null},Z$a=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.J=1E3/(b-a.D);a.D=b;$$a(a,a.progress);1==a.progress?(a.j=0,a4(a),a.onFinish(),a.Aq()):a.bd()&&a.pI()},$$a=function(a,b){"function"===typeof a.I&&(b=a.I(b));
a.coords=Array(a.u.length);for(var c=0;c<a.u.length;c++)a.coords[c]=(a.T[c]-a.u[c])*b+a.u[c]},aab=function(a,b){g.fb.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.J;this.state=b.j},c4=function(a,b,c,d,e){b4.call(this,b,c,d,e);
this.element=a},bab=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
c4.call(this,a,b,c,d,e)},cab=function(a){g.C.call(this);
this.u=a||window;this.j=[]},d4=function(a){return a.baseUrl||null},e4=function(a,b){return g.vm(g.eh(a,b),function(c){return!!c})},dab=function(a,b,c){function d(R){var ba=R.hovercardButton;
if(!ba)return null;ba=ba.subscribeButtonRenderer;if(!ba)return null;var O=f(ba.unsubscribedButtonText),sa=f(ba.subscribedButtonText);if(ba.subscribed){var na=f(ba.subscriberCountWithUnsubscribeText);var ya=f(ba.subscriberCountText)}else na=f(ba.subscriberCountText),ya=f(ba.subscriberCountWithSubscribeText);var Ea=null;if(R.signinEndpoint){Ea=Y3(R,"signinEndpoint","webNavigationEndpointData","url");if(!Ea){var Ya,Ma;Ea=null==(Ma=g.M(null==(Ya=ba.signInEndpoint)?void 0:Ya.commandMetadata,g.T2))?void 0:
Ma.url}if(!Ea)return null}return O&&(sa||Ea)?{subscribed:ba.subscribed,subscribeText:O,subscribeCount:na,unsubscribeText:sa,unsubscribeCount:ya,enabled:ba.enabled,signinUrl:Ea,classic:R.useClassicSubscribeButton}:null}
function e(R){if(R){var ba=[],O=R.videoId;O&&ba.push("v="+O);(O=R.playlistId)&&ba.push("list="+O);(R=R.startTimeSeconds)&&ba.push("t="+R);return"/watch?"+ba.join("&")}}
function f(R){if(!R)return null;var ba=R.simpleText;return ba?ba:R.runs?g.eh(R.runs,function(O){return O.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,r=null,w=null,x=null,z=!1,B=null,E=null,G=null,F=null,K=null,P=null;if("VIDEO"===h)g.M(l,g.lJ)?m=g.M(l,g.lJ).url:(P=g.M(l,g.jJ),m=e(P)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,r=f(p.text),p="LIVE"===p.style):r=f(b.videoDuration);else if("PLAYLIST"===h)g.M(l,g.lJ)?m=g.M(l,g.lJ).url:(P=g.M(l,g.jJ),m=e(P)),n=!1,q=a,w=f(b.playlistLength);else if("CHANNEL"===
h){if(z=Y3(l,"browseEndpoint","browseId"))x=z,m="/channel/"+x;n=!1;q="new";(z=!!b.isSubscribe)?B=d(b):E=f(b.subscribersText)}else"WEBSITE"===h?((G=Y3(l,"urlEndpoint","url"))&&(m=G),n=!0,q="new",G=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(F=f(b.productPrice)),b.additionalFeesText&&(K=f(b.additionalFeesText)),(n=Y3(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=Y3(b,"title","accessibility","accessibilityData","label");var Q=b.endpoint?b.endpoint.clickTrackingParams:null,
Y="";if(b.metadata){var V=f(b.metadata);V&&(Y=V)}return{id:"element-"+c,type:h,title:f(b.title),metadata:Y,callToAction:f(b.callToAction),tS:b.image,iconUrl:G,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,WB:p,playlistLength:w,channelId:x,subscribeButton:B,subscribersText:E,isSubscribe:z,Dt:m||null,j3:n,sessionData:Q?{itct:Q}:null,e8:q,yA:a?a:null,isPlaceholder:b.isPlaceholder,
impressionUrls:e4(b.impressionUrls||[],d4),V2:e4(b.hovercardShowUrls||[],d4),clickUrls:e4(l.loggingUrls||[],d4),visualElement:g.mC(b.trackingParams),productPrice:F,additionalFeesText:K,watchEndpoint:P||null}},eab=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:e4(a.impressionUrls||[],d4),elements:e4(a.elements||[],function(d,e){return dab(b,d,e)})};
a.trackingParams&&(c.visualElement=g.mC(a.trackingParams));return c},fab=function(a){g.qR.call(this,a);
this.B=this.endscreen=null;this.j={};this.D={};this.C=this.u=null;this.J=[];this.Y=!0;this.I=0;a=a.V();this.T=g.QH(a)||"profilepage"===a.Fa;this.ma=a.experiments.kb("web_rounded_thumbnails");this.events=new g.MF(this);g.D(this,this.events);this.events.S(this.player,g.KB("creatorendscreen"),this.onCueRangeEnter);this.events.S(this.player,g.LB("creatorendscreen"),this.onCueRangeExit);this.events.S(this.player,"resize",this.Eb);this.events.S(window,"focus",this.R6);this.load();var b=g.Ke("STYLE");(g.ye("HEAD")[0]||
document.body).appendChild(b);g.eb(this,function(){g.Pe(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},gab=function(a){return a.player.getVideoData().D?"current":a.T?"new":"current"},f4=function(a){return"creator-endscreen-editor"===a.player.V().playerStyle},hab=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.B&&a.B.abort();c={method:"POST",onFinish:function(e){var f=a.B=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=eab(f,gab(a))));g4(a,f)},
urlParams:{v:c},withCredentials:!0};a.T&&(c.urlParams.ptype="embedded");var d=b.Fw;d&&(c.postParams={ad_tracking:d});if(b=g.YBa(b))if(b=g.Md(b),b=g.Jd(b))a.B=g.uw(b,c)},g4=function(a,b,c){c=void 0===c?!0:c;
a.player.Rf("creatorendscreen");a.u&&(a.u.dispose(),a.u=null,a.C.dispose(),a.C=null);for(var d=g.t(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.D={};0<a.J.length&&(a.J.forEach(function(l){l.dispose()}),a.J.length=0);
a.I=0;if((a.endscreen=b)&&b.elements){c&&iab(a);c=[];d=new g.IB(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.V().u||(a.u=new g.U({G:"div",N:"ytp-ce-shadow"}),g.GQ(a.player,a.u.element,4),a.C=new g.jO(a.u,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=jab(a,e);if(f){a.j[e.id]=f;a.D[e.id]=e;g.GQ(a.player,f.element,4);var h=new g.IB(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);kab(a,f,e)}else g.mB(new g.qx("buildEndscreenElement null",
e))}a.player.Se(c);a.Eb()}},iab=function(a){var b=g.pC(),c=g.qC();
c&&b&&a.endscreen.visualElement&&g.$v(g.wM)(void 0,c,b,a.endscreen.visualElement)},jab=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={G:"div",Ja:["ytp-ce-element","ytp-ce-video"],X:{tabindex:"0","aria-label":b.yA||"","aria-hidden":"true"},W:[{G:"div",N:"ytp-ce-element-shadow"},{G:"div",N:"ytp-ce-covering-image",X:h4(b)},{G:"div",N:"ytp-ce-covering-shadow-top"},{G:"a",N:"ytp-ce-covering-overlay",X:{href:i4(a,b.Dt),tabindex:"-1"},W:[{G:"div",Ja:["ytp-ce-video-title","ytp-webkit-ellipsis"],X:{dir:g.Co(b.title||"")},ra:b.title},{G:"div",N:b.WB?"ytp-ce-live-video-duration":"ytp-ce-video-duration",ra:b.videoDuration||
void 0}]}]};c=new g.U(a);break;case "PLAYLIST":a={G:"div",Ja:["ytp-ce-element","ytp-ce-playlist"],X:{tabindex:"0","aria-label":b.yA||"","aria-hidden":"true"},W:[{G:"div",N:"ytp-ce-element-shadow"},{G:"div",N:"ytp-ce-covering-image",X:h4(b)},{G:"div",N:"ytp-ce-covering-shadow-top"},{G:"a",N:"ytp-ce-covering-overlay",X:{href:i4(a,b.Dt),tabindex:"-1"},W:[{G:"div",Ja:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],X:{dir:g.Co(b.title||"")},ra:b.title},{G:"div",N:"ytp-ce-playlist-count",W:[{G:"div",N:"ytp-ce-playlist-icon"},
{G:"div",N:"ytp-ce-playlist-count-text",ra:b.playlistLength||void 0}]}]}]};c=new g.U(a);break;case "CHANNEL":c={G:"div",Ja:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],X:{tabindex:"0","aria-label":b.yA||"","aria-hidden":"true"},W:[{G:"div",N:"ytp-ce-element-shadow"},{G:"div",N:"ytp-ce-expanding-overlay",W:[{G:"div",N:"ytp-ce-expanding-overlay-hider"},{G:"div",N:"ytp-ce-expanding-overlay-background"},{G:"div",N:"ytp-ce-expanding-overlay-content",W:[{G:"div",
N:"ytp-ce-expanding-overlay-body",W:[{G:"div",N:"ytp-ce-expanding-overlay-body-padding",W:[{G:"a",Ja:["ytp-ce-channel-title","ytp-ce-link"],X:{href:i4(a,b.Dt),target:"_blank",tabindex:"-1",dir:g.Co(b.title||"")},ra:b.title},b.subscribeButton?{G:"div",N:"ytp-ce-subscribe-container",W:[{G:"div",N:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{G:"div",N:"ytp-ce-channel-subscribers-text",ra:b.subscribersText}:"",b.metadata?{G:"div",Ja:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],
ra:b.metadata}:""]}]}]}]},{G:"div",N:"ytp-ce-expanding-image",X:h4(b)}]};c=new g.U(c);var d=g.ze(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.mo(d,"ytp-ce-subscribe-button");if(a.player.V().u){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.uS(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.J.push(e)}break;case "WEBSITE":a={G:"div",Ja:["ytp-ce-element","ytp-ce-website"],X:{tabindex:"0","aria-label":b.yA||"","aria-hidden":"true"},W:[{G:"div",N:"ytp-ce-element-shadow"},{G:"div",N:"ytp-ce-expanding-overlay",W:[{G:"div",N:"ytp-ce-expanding-overlay-hider"},{G:"div",N:"ytp-ce-expanding-overlay-background"},{G:"div",N:"ytp-ce-expanding-overlay-content",W:[{G:"div",N:"ytp-ce-expanding-overlay-body",
W:[{G:"div",N:"ytp-ce-expanding-overlay-body-padding",W:[{G:"div",N:"ytp-ce-website-title",X:{dir:g.Co(b.title||"")},ra:b.title},{G:"div",N:"ytp-ce-website-metadata",ra:b.metadata},{G:"a",Ja:["ytp-ce-website-goto","ytp-ce-link"],X:{href:i4(a,b.Dt),target:"_blank",tabindex:"-1"},ra:b.callToAction}]}]}]}]},{G:"div",N:"ytp-ce-expanding-image",X:h4(b)},{G:"div",N:"ytp-ce-expanding-icon",X:lab(b.iconUrl)}]};c=new g.U(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={G:"div",N:"ytp-ce-merchandise-price-container",
W:[{G:"div",N:"ytp-ce-merchandise-price",ra:b.productPrice}]},b.additionalFeesText&&c.W.push({G:"div",N:"ytp-ce-merchandise-additional-fees",ra:b.additionalFeesText})),a={G:"div",Ja:["ytp-ce-element","ytp-ce-merchandise"],X:{tabindex:"0","aria-label":b.yA||"","aria-hidden":"true"},W:[{G:"div",N:"ytp-ce-element-shadow"},{G:"div",N:"ytp-ce-expanding-overlay",W:[{G:"div",N:"ytp-ce-expanding-overlay-hider"},{G:"div",N:"ytp-ce-expanding-overlay-background"},{G:"div",N:"ytp-ce-expanding-overlay-content",
W:[{G:"div",N:"ytp-ce-expanding-overlay-body",W:[{G:"div",N:"ytp-ce-expanding-overlay-body-padding",W:[{G:"div",N:"ytp-ce-merchandise-title",X:{dir:g.Co(b.title||"")},ra:b.title},c,{G:"div",N:"ytp-ce-merchandise-metadata",ra:b.metadata},{G:"a",Ja:["ytp-ce-merchandise-goto","ytp-ce-link"],X:{href:i4(a,b.Dt),target:"_blank",tabindex:"-1"},ra:b.callToAction}]}]}]}]},{G:"div",N:"ytp-ce-expanding-image",X:h4(b)},{G:"div",N:"ytp-ce-merchandise-invideo-cta-container",W:[{G:"div",N:"ytp-ce-merchandise-invideo-cta",
ra:b.callToAction||void 0}]}]},c=new g.U(a)}b.isPlaceholder&&g.mo(c.element,"ytp-ce-placeholder");return c},h4=function(a){if(a.tS)var b=a.tS.thumbnails;
return lab(b?b[b.length-1].url:null)},lab=function(a){return a?{style:"background-image: url("+a+")"}:{}},kab=function(a,b,c){function d(m){m&&(b.Qa("blur",function(){"none"!=m.style.display&&a.Y&&m.focus()}),b.S(m,"focus",f),b.S(m,"blur",h))}
function e(m){a.I+=m;0<a.I?(g.mo(b.element,"ytp-ce-force-expand"),j4(a,c.id,!0)):(g.oo(b.element,"ytp-ce-force-expand"),g.oo(b.element,"ytp-ce-element-hover"),j4(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Qa("mouseenter",function(){mab(a,b,c)});
b.Qa("mouseleave",function(){nab(a,b,c)});
a.player.V().u||b.Qa("click",function(){g.mo(b.element,"ytp-ce-element-hover")});
b.Qa("click",function(m){oab(a,c,m)});
b.Qa("keypress",function(m){oab(a,c,m)});
b.Qa("focus",function(){mab(a,b,c)});
b.Qa("blur",function(){nab(a,b,c)});
b.Qa("touchstart",function(){mab(a,b,c)});
var l=g.Be("ytp-ce-expanding-overlay-hider",b.element);l&&b.S(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.oo(b.element,"ytp-ce-element-hover");g.oo(b.element,"ytp-ce-force-expand")});
b.Qa("keydown",function(m){a.Y=9===m.keyCode&&!m.shiftKey});
d(g.Be("ytp-sb-subscribe",b.element));d(g.Be("ytp-sb-unsubscribe",b.element));b.Qa("focus",f);b.Qa("blur",h)},oab=function(a,b,c){if(b.Dt&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.lo(d,"ytp-ce-element");){g.lo(d,"subscribe-label")&&pab(a,b);
if(g.lo(d,"ytp-ce-channel-subscribe"))return;d=g.Qe(d)}if(!d||g.lo(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])nab(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.e8)pab(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Md(i4(a,b.Dt)),g.kL(g.Jd(c),void 0,b.sessionData);else{var e=g.iI(a.player.V())||a.player.getVideoData().D,f=function(){var h=i4(a,b.Dt),l=b.sessionData,m=b.watchEndpoint,n=g.fw(h);e&&n&&(n.v||n.list)?a.player.Ln(n.v,
l,n.list,!1,void 0,m||void 0):g.iL(h,l)};
pab(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},i4=function(a,b){a=a.player.V();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.rI(a)+b}else return"";return b},mab=function(a,b,c){g.lo(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.mo(b.element,"ytp-ce-element-hover"):a.player.V().u?(new g.eo(function(){g.mo(b.element,"ytp-ce-element-hover")},200)).start():g.mo(b.element,"ytp-ce-element-hover"),k4(a,c.V2),j4(a,c.id,!0))},nab=function(a,b,c){g.oo(b.element,"ytp-ce-element-hover");
g.oo(b.element,"ytp-ce-force-expand");j4(a,c.id,!1)},j4=function(a,b,c){a.u&&(c?a.C.show():a.C.hide());
for(var d=g.t(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.qo(a.j[e].element,"ytp-ce-element-shadow-show",c)},k4=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||f4(a))c&&c();else{b=qab(a,b);var e=0,f=!1,h=new g.eo(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.fz(b[a],d)}},pab=function(a,b,c){k4(a,b.clickUrls,c);
(a=g.qC())&&b.j3&&g.DM(a,b.visualElement)},qab=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(rab(b[d],c));return a},rab=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},sab=function(a){return"string"===typeof a?a:""},l4=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},tab=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},m4=function(a){return a.value?a.value:null},n4=function(a){if(!a)return null;
var b=g.Md(sab(a.value));b=g.Jd(b);if(!b)return null;var c=l4(a.target,uab,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new tab(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},vab=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},yab=function(a){if(!a)return null;
var b=l4(a.type,wab),c=l4(a.trigger,xab);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=n4(a?a:null);return b?new vab(b,c,a):null},zab=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},Aab=function(a,b){return g.jb(a.action,b)},Bab=function(a,b){this.context=a;
this.j=b},Cab=function(a){return a.customMessage?o4("div","iv-card-message",a.customMessage):""},p4=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{G:"div",N:"iv-card-image",X:{style:a},W:c}},Dab=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.t(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(o4("li","",c.value));return{G:"ul",N:"iv-card-meta-info",W:b}},o4=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Co(c);return{G:a,X:b,ra:c}},Eab=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.IA&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.IA+");");c.dir=g.Co(a.customMessage);var d=[{G:"span",ra:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({G:"span",N:"iv-card-link-icon"}));return{G:"div",Ja:b,X:c,W:d}},q4=function(a,b,c,d){if(d){b=g.t(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.Si.click,5)}},Fab=function(a,b){this.merchant=a;
this.price=b},Gab=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},Hab=function(a,b){return b?b:Gab(a)?"current":"new"},r4=function(a,b){g.C.call(this);
var c=this;this.element=a;this.context=b;this.xb=!1;this.Ya=new Map;this.eb=new Map;this.context.F.addEventListener(g.KB("annotations_module"),function(d){(d=c.Ya.get(d))&&d.apply(c)});
this.context.F.addEventListener(g.LB("annotations_module"),function(d){(d=c.eb.get(d))&&d.apply(c)})},s4=function(a,b,c,d,e,f,h){a.context.j.Qa(b,"click",function(l){a.qI(c,d,e,f||[],h||0,l)});
a.context.j.Qa(b,"touchstart",function(){a.xb=!1});
a.context.j.Qa(b,"touchmove",function(){a.xb=!0})},Iab=function(a){var b;
return(null==(b=g.M(a,g.lJ))?0:b.url)?g.M(a,g.lJ).url:(a=g.M(a,g.jJ))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},t4=function(a,b,c){return{OT:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
kX:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
xH:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},Jab=function(a,b,c){r4.call(this,b,c);
var d=this;this.F=a;this.eventId=null;this.Ra=this.Sb=this.B=this.isInitialized=!1;this.ya=null;this.cards=[];this.Ib=this.T=this.Ma=this.D=this.Sa=this.j=null;this.ma=[];this.oa=this.J=this.Zf=this.Ka=null;this.I=0;this.Fa=new g.eo(function(){},c.Z.fh?4E3:3E3);
g.D(this,this.Fa);this.ob=new g.eo(function(){});
g.D(this,this.ob);this.Aa=new Bab(c,function(e,f,h,l,m,n){s4(d,e,f,h,l,m,n)});
this.Y=new g.U({G:"div",N:"iv-drawer",X:{id:"iv-drawer"},W:[{G:"div",N:"iv-drawer-header",X:{"aria-role":"heading"},W:[{G:"span",N:"iv-drawer-header-text"},{G:"button",Ja:["iv-drawer-close-button","ytp-button"],X:{"aria-label":"Hide cards",tabindex:"0"}}]},{G:"div",N:"iv-drawer-content"}]});g.D(this,this.Y);this.C=this.Y.element;this.jb=new g.jO(this.Y,330);g.D(this,this.jb);this.Tb=g.Be("iv-drawer-header-text",this.C);this.u=g.Be("iv-drawer-content",this.C);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Sb&&u4(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Sb=d.B)&&v4(d)});
this.F.addEventListener("videodatachange",this.zs.bind(this))},Kab=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){u4(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){v4(a)});
var c=b.headerText;g.Se(a.Tb,c);a.T&&a.T.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ka=g.mC(b.trackingParams);a.J=g.mC(b.closeTrackingParams);a.Zf=g.mC(b.iconTrackingParams)},Lab=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.I,d=a.F.V().experiments.kb("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.SB(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,Si:{},uo:null,Vk:e.trackingParams?g.mC(e.trackingParams):null,Zf:f&&f.trackingParams?g.mC(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
IA:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};w4(a,b)}else{var h;if(null==(h=b.content)?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=null==(e=b.content)?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.SB(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:x4(a,c,b,f),sponsored:!1,Si:t4(f,e,f.command),uo:f.trackingParams?g.mC(f.trackingParams):null,Vk:e.trackingParams?g.mC(e.trackingParams):null,Zf:l&&l.trackingParams?g.mC(l.trackingParams):null,imageUrl:y4(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.SB(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,IA:null,title:f.title?g.SB(f.title):"",customMessage:f.callToAction?g.SB(f.callToAction):"",url:g.M(f.command,g.lJ).url?n4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.M(f.command,g.lJ).url}):null,onClickCommand:null};w4(a,b)}else{var m;if(null==(m=b.content)?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(f=b.content)?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"collaborator",teaserText:g.SB(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:x4(a,c,b,e),sponsored:!1,Si:t4(e,f,e.endpoint),uo:e.trackingParams?g.mC(e.trackingParams):null,Vk:f.trackingParams?g.mC(f.trackingParams):null,Zf:l&&l.trackingParams?g.mC(l.trackingParams):null,channelId:g.M(e.endpoint,z4).browseId,customMessage:e.customText?g.SB(e.customText):null,dW:y4(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.SB(e.channelName):"",metaInfo:[e.subscriberCountText?g.SB(e.subscriberCountText):""],url:n4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.M(e.endpoint,z4).canonicalBaseUrl?g.M(e.endpoint,z4).canonicalBaseUrl:"/channel/"+g.M(e.endpoint,z4).browseId}),onClickCommand:null};w4(a,b)}else{var n;if(null==(n=b.content)?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(l=b.content)?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"playlist",teaserText:g.SB(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:x4(a,c,b,e),sponsored:!1,Si:t4(e,f,e.action),uo:e.trackingParams?g.mC(e.trackingParams):null,Vk:f.trackingParams?g.mC(f.trackingParams):null,Zf:l&&l.trackingParams?g.mC(l.trackingParams):null,yD:y4(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.SB(e.customMessage):null,playlistVideoCount:g.SB(e.playlistVideoCount),title:e.playlistTitle?g.SB(e.playlistTitle):"",metaInfo:[e.channelName?g.SB(e.channelName):
"",e.videoCountText?g.SB(e.videoCountText):""],url:n4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:Iab(e.action)}),onClickCommand:null};w4(a,b)}else{var p;if(null==(p=b.content)?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=null==(q=b.content)?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"video",teaserText:g.SB(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:x4(a,c,b,e),sponsored:!1,Si:t4(e,f,e.action),uo:e.trackingParams?g.mC(e.trackingParams):null,Vk:f.trackingParams?g.mC(f.trackingParams):null,Zf:l&&l.trackingParams?g.mC(l.trackingParams):null,yD:y4(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.SB(e.lengthString):null,customMessage:e.customMessage?g.SB(e.customMessage):null,title:e.videoTitle?g.SB(e.videoTitle):"",metaInfo:[e.channelName?g.SB(e.channelName):
"",e.viewCountText?g.SB(e.viewCountText):""],isLiveNow:!!e.badge,url:n4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:Iab(e.action)}),onClickCommand:null};w4(a,b)}}}}}a.I++},y4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},x4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},Nab=function(a,b){if(b=Mab(a,b))b===a.j&&(a.j=null),a.F.removeCueRange(b.gg.id),g.Pe(b.VJ),g.qb(a.cards,b),a.xE(),A4(a)},u4=function(a,b,c){if(!a.B){a.jb.show();
a.Sa=new g.eo(function(){g.mo(a.context.F.getRootNode(),g.HW.IV_DRAWER_OPEN)},0);
a.Sa.start();a.ya=g.wz(a.u,"mousewheel",function(h){a.Fa.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.u.scrollTop+=h});
a.B=!0;var d=g.qC();d&&a.Ka&&a.J&&g.BM(d,[a.Ka,a.J]);b={TRIGGER_TYPE:b};for(var e=g.t(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.yU||(f.yU=!0,Oab(a.context.logger,f.gg.Si.OT,b)),d&&g.BM(d,[f.gg.uo]);X3(a.F);c&&(a.D=new g.eo(function(){a.Ma=a.T;a.Ib.focus()},330),a.D.start())}},v4=function(a){a.B&&(a.jb.hide(),g.xz(a.ya),a.ya=null,g.oo(a.context.F.getRootNode(),g.HW.IV_DRAWER_OPEN),a.B=!1,X3(a.F),a.D&&a.D.stop(),a.D=new g.eo(function(){a.Ma&&(a.Ma.focus(),a.Ma=null)},330),a.D.start())},Qab=
function(a){g.no(a.wb(),[g.HW.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.GQ(a.F,a.C,5);Pab(a);a.T=g.Be("ytp-cards-button",a.F.getRootNode());a.Ib=g.Be("iv-drawer-close-button",a.C);a.isInitialized=!0},Pab=function(a){var b=g.Be("iv-drawer-close-button",a.C);
a.context.j.Qa(b,"click",a.h1,a);a.context.j.Qa(a.u,"touchend",function(){a.Fa.start()});
a.context.j.Qa(a.u,"scroll",a.B1,a);a.context.u.subscribe("onHideControls",function(){a.Ra=!0});
a.context.u.subscribe("onShowControls",function(){a.Ra=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.Ra=g.lo(a.F.getRootNode(),"ytp-autohide")});
a.ma.push(g.Qz("iv-button-shown",a.w3,a));a.ma.push(g.Qz("iv-button-hidden",a.v3,a));a.ma.push(g.Qz("iv-teaser-shown",a.OY,a));a.ma.push(g.Qz("iv-teaser-hidden",a.x3,a));a.ma.push(g.Qz("iv-teaser-clicked",a.MY,a))},Rab=function(a,b){var c;
return b.onClickCommand&&"engagement-panel-error-corrections"===(null==(c=g.M(b.onClickCommand,g.S7a))?void 0:c.targetId)?(a.oa=b,!0):!1},Sab=function(a,b){a.oa=b;
var c=a.F.getVideoData();if(!c)return!1;c=a.F.K("embeds_web_enable_video_data_refactoring_offline_and_progress_bar")?g.nJ(c):c.multiMarkersPlayerBarRenderer;if(null==c?0:c.markersMap)for(var d,e=0;(null==(d=c)?void 0:d.markersMap.length)>e;e++){var f=void 0,h=null==(f=c)?void 0:f.markersMap[e];if("ERROR_CORRECTION_MARKERS"===h.key&&(f=void 0,(h=null==(f=h.value)?void 0:f.markers)&&0<h.length))return d=void 0,b.startMs=(null==(d=g.M(h[0],g.lNa))?void 0:d.timeRangeStartMillis)||0,a.oa=null,!0}return!1},
w4=function(a,b){if(!Rab(a,b)||Sab(a,b)){var c=Uab(a,b);
if(c){var d={gg:b,VJ:c.element,yU:!1};if(!b.onClickCommand){a.isInitialized||Qab(a);Nab(a,b.id);var e=Vab(a,d);g.Ab(a.cards,e,0,d);c.Da(a.u,e);a.xE()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.B||(a.j=d,A4(a),Wab(a,d),u4(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.F.getCurrentTime(),5E3>c&&c>b.startMs&&Xab(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){Xab(a,d)}),A4(a))}}},Uab=function(a,b){switch(b.type){case "simple":var c=a.Aa;
var d=b.displayDomain?{G:"div",N:"iv-card-image-text",ra:b.displayDomain}:void 0;var e=Eab(b);d={G:"div",Ja:["iv-card"],W:[{G:"a",N:"iv-click-target",X:{href:b.url?m4(b.url)||"":""},W:[p4(b.imageUrl,d),{G:"div",N:"iv-card-content",W:[o4("h2",void 0,b.title),e]}]}]};d=new g.U(d);q4(c,g.Ae("iv-click-target",d.element),b,b.url);b=d;break;case "collaborator":c=a.Aa;d={G:"div",Ja:["iv-card","iv-card-channel"],W:[{G:"a",Ja:["iv-click-target"],X:{href:m4(b.url)||"","data-ytid":b.channelId},W:[p4(b.dW),{G:"div",
N:"iv-card-content",W:[Cab(b),{G:"h2",N:"iv-card-primary-link",ra:b.title},Dab(b)]}]}]};d=new g.U(d);q4(c,g.Ae("iv-click-target",d.element),b,b.url);b=d;break;case "playlist":c=a.Aa;d={G:"div",Ja:["iv-card","iv-card-playlist"],W:[{G:"a",N:"iv-click-target",X:{href:m4(b.url)||""},W:[p4(b.yD,{G:"div",N:"iv-card-image-overlay",W:[{G:"span",N:"iv-card-playlist-video-count",ra:b.playlistVideoCount}]}),{G:"div",N:"iv-card-content",W:[Cab(b),o4("h2","iv-card-primary-link",b.title),Dab(b)]}]}]};d=new g.U(d);
q4(c,g.Ae("iv-click-target",d.element),b,b.url);b=d;break;case "productListing":c=a.Aa;var f=!g.nb(b.offers);d=["iv-card"];e="";var h=Eab(b);f&&(d.push("iv-card-product-listing"),e="iv-card-primary-link",h=b.offers[0],f=[],h.price&&f.push({G:"div",N:"iv-card-offer-price",ra:h.price}),h.merchant&&f.push({G:"div",N:"iv-card-offer-merchant",ra:h.merchant}),h={G:"div",W:f});f=b.url?m4(b.url)||"":"";d={G:"div",Ja:d,X:{tabindex:"0"},W:[{G:"a",Ja:["iv-card-image","iv-click-target"],X:{style:"background-image: url("+
b.imageUrl+");",href:f,"aria-hidden":"true",tabindex:"-1"}},{G:"div",N:"iv-card-content",W:[b.sponsored?{G:"div",N:"iv-card-sponsored",W:["Sponsored",{G:"div",N:"iv-ad-info-container",W:[{G:"div",N:"iv-ad-info",ra:"{{adInfo}}"},{G:"div",N:"iv-ad-info-icon-container",W:[{G:"div",N:"iv-ad-info-icon"},{G:"div",N:"iv-ad-info-callout"}]}]}]}:"",{G:"a",N:"iv-click-target",X:{href:f},W:[o4("h2",e,b.title),h]}]}]};d=new g.U(d);e=g.Ke("span");g.Se(e,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
d.ze(e,"adInfo");q4(c,g.Ae("iv-click-target",d.element),b,b.url);b=d;break;case "video":c=a.Aa;d=b.videoDuration?{G:"span",N:"iv-card-video-duration",ra:b.videoDuration}:void 0;e=b.isLiveNow?{G:"span",Ja:["yt-badge","yt-badge-live"],ra:"LIVE NOW"}:null;f={G:"div",Ja:["iv-card","iv-card-video"],W:[{G:"a",N:"iv-click-target",X:{href:(null==(h=b.url)?void 0:m4(h))||""},W:[p4(b.yD,d),{G:"div",N:"iv-card-content",W:[Cab(b),o4("h2","iv-card-primary-link",b.title),Dab(b),e]}]}]};d=new g.U(f);q4(c,g.Ae("iv-click-target",
d.element),b,b.url);b=d;break;default:return null}a.F.V().experiments.kb("web_rounded_containers")&&g.mo(b.element,"ytp-rounded-info");return b},Vab=function(a,b){if(0===a.cards.length)return 0;
a=g.kb(a.cards,function(c){return b.gg.startMs>c.gg.startMs||b.gg.startMs===c.gg.startMs&&b.gg.timestamp>=c.gg.timestamp?!0:!1});
return-1===a?0:a+1},Yab=function(a){return a.j?"productListing"===a.j.gg.type:g.Jk(a.cards,function(b){return"productListing"===b.gg.type})},A4=function(a){g.qo(a.F.getRootNode(),"ytp-cards-shopping-active",Yab(a))},Xab=function(a,b){if(!g.lo(a.F.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.qC(),d=a.j?a.j.gg.Zf:a.Zf;
c&&d&&g.CM(c,[d]);a.j=b;A4(a)}(c=a.isInitialized&&"none"==a.wb().style.display)||(c=a.context.F.getPlayerState(),d=0===c&&0===a.context.F.getCurrentTime(),c=!(1===c||3===c||d));c||b.gg.teaserDurationMs&&a.F.oz(!0,{teaserText:b.gg.teaserText,durationMs:b.gg.teaserDurationMs,onClickCommand:b.gg.onClickCommand});a.ob.isActive()||((!a.B||!a.Fa.isActive()&&a.Ra)&&Wab(a,b),a.ob.start(910+b.gg.teaserDurationMs))}},Wab=function(a,b){a.Y.tb?(b=new b4([0,
a.u.scrollTop],[0,b.VJ.offsetTop],600,W$a),a.context.B.Qa(b,"animate",function(c){a.u.scrollTop=c.y}),a.context.B.Qa(b,"finish",function(c){a.u.scrollTop=c.y}),b.play()):(g.wN(a.Y,!0),a.u.scrollTop=b.VJ.offsetTop,g.wN(a.Y,!1))},B4=function(a){return a.j&&a.j.gg?a.j.gg:a.cards[0]&&a.cards[0].gg?a.cards[0].gg:null},Mab=function(a,b){return g.jb(a.cards,function(c){return c.gg.id===b})},C4=function(a,b,c){r4.call(this,a,b);
this.annotation=c;this.isActive=!1},Zab=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},D4=function(a,b,c){C4.call(this,a,b,c);
this.u=null;this.J=!1;this.B=null;this.C=!1;this.j=this.I=this.D=null},$ab=function(a,b){var c=void 0===c?0:c;
var d=U$a(b).width;g.Al(b,d);c=new bab(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,V$a);g.D(a,c);a.context.B.Qa(c,"begin",function(){g.Ml(b,!0)});
c.play()},cbb=function(a,b){if(b.channel_name){var c=a.createElement({G:"div",
Ja:["iv-branding-context-name"],ra:b.channel_name}),d=a.createElement({G:"div",Ja:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.uS(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signInUrl,a.context.F),a.j.Da(d));var f=a.createElement({G:"div",Ja:["iv-branding-context-subscribe-caret"]}),h=a.createElement({G:"div",Ja:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.Ml(h,!1);a.context.Z.K("web_rounded_containers")&&g.mo(h,"ytp-rounded-branding-context");var l=a.createElement({G:"div",Ja:["branding-context-container-outer"]});l.appendChild(h);g.ul(l,"right",b.image_width+"px");g.Me(a.wb(),l);a.B=new g.eo(function(){abb(a,h,l)},500);
g.D(a,a.B);a.context.j.Qa(a.wb(),"mouseover",function(){bbb(a,h,l,f,b.image_height)});
a.context.j.Qa(a.wb(),"mouseout",function(){a.B.start()})}},bbb=function(a,b,c,d,e){a.B.stop();
if(!a.C){var f=g.Ll(b);a.j||(b.style.width=g.zl(f.width,!0),c.style.width=g.zl(f.width,!0));g.ul(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.ul(d,"right","1px");a.C=!0;g.Ml(b,!0);a.D=new g.eo(function(){g.mo(this.wb(),"iv-branding-active")},0,a);
a.D.start()}},abb=function(a,b,c){g.oo(a.wb(),"iv-branding-active");
a.I=new g.eo(function(){g.Ml(b,!1);a.j||(c.style.width=g.zl(0,!0))},250);
a.I.start();a.C=!1},dbb=function(a,b,c,d,e,f,h){this.j=a;
this.B=b;this.Z=c;this.videoData=d;this.logger=e;this.F=f;this.u=h},ebb=function(a,b,c){C4.call(this,a,b,c);
var d=this;this.T=this.isCollapsed=this.Y=!1;this.I=5E3;this.u=this.B=this.j=this.C=null;this.J=this.createElement({G:"div",Ja:["iv-promo-contents"]});this.D=new g.eo(function(){d.j.setAttribute("aria-hidden","true");g.Ml(d.B,!1);g.Ml(d.u,!0)},700,this);
g.D(this,this.D)},gbb=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.I=b.collapsedelay_ms||a.I;var d=["iv-promo","iv-promo-inactive"];a.wb().setAttribute("aria-hidden","true");a.wb().setAttribute("aria-label","Promotion");a.wb().tabIndex=0;var e=a.annotation.cf(),f=b.image_url;if(f){var h=a.createElement({G:"div",Ja:["iv-promo-img","iv-click-target"]});f=a.createElement({G:"img",X:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?
(f=a.createElement({G:"span",N:"iv-promo-video-duration",ra:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({G:"span",N:"iv-promo-playlist-length",ra:b.playlist_length.toString()}),h.appendChild(f));e&&s4(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({G:"a",N:"iv-promo-txt"}),g.Wd(f,m4(e)),a.j=f):a.j=a.createElement({G:"div",N:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({G:"p",W:[{G:"strong",ra:b.text_line_1}]});
var m=a.createElement({G:"p",W:[{G:"span",N:"iv-promo-link",ra:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({G:"button",Ja:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({G:"button",Ja:["iv-button","iv-promo-button"],W:[{G:"span",N:"iv-button-content",ra:f}]});var p=a.createElement({G:"div",N:"iv-promo-button-container"});p.appendChild(f);e&&s4(a,a.wb(),e,a.annotation.id,b.session_data,void 0,c)}g.mo(a.j,"iv-click-target");
e&&s4(a,a.j,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({G:"p",W:[{G:"span",ra:b.text_line_1}]}),m=a.createElement({G:"p",W:[{G:"strong",ra:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({G:"span",Ja:["yt-badge","iv-promo-badge-live"],ra:"LIVE NOW"})),g.mo(a.j,"iv-click-target"),e&&s4(a,a.j,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.j.appendChild(l);m&&a.j.appendChild(m);a.J.appendChild(a.j);p&&a.J.appendChild(p);
c=a.createElement({G:"div",N:"iv-promo-actions"});a.u=a.createElement({G:"button",Ja:["iv-promo-expand","ytp-button"]});a.u.title="Expand";a.context.j.Qa(a.u,"click",function(q){fbb(a,5E3,q)});
c.appendChild(a.u);g.Ml(a.u,!1);a.context.j.Qa(a.wb(),"mouseover",a.A2,a);a.context.j.Qa(a.wb(),"mouseout",a.z2,a);a.context.j.Qa(a.wb(),"touchend",function(q){fbb(a,5E3,q)});
a.B=a.createElement({G:"button",Ja:["iv-promo-close","ytp-button"]});a.B.title="Close";a.context.j.Qa(a.B,"click","cta"===a.annotation.style&&b.text_line_3?a.t2:a.s2,a);c.appendChild(a.B);g.no(a.wb(),d);h&&(g.Me(a.wb(),h),n&&h.appendChild(n));g.Me(a.wb(),a.J);g.Me(a.wb(),c)},fbb=function(a,b,c){c.stopPropagation();
hbb(a);ibb(a,b);a.j.focus()},jbb=function(a){a.isCollapsed||a.T||a.C||(g.mo(a.wb(),"iv-promo-collapsed"),a.isCollapsed=!0,a.D.start())},hbb=function(a){a.D.stop();
a.isCollapsed&&(g.po(a.wb(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.Ml(a.u,!1),g.Ml(a.B,!0))},ibb=function(a,b){a.C||(a.C=g.uf(function(){kbb(this);
jbb(this)},b,a))},kbb=function(a){a.C&&(g.Da.clearTimeout(a.C),a.C=null)},lbb=function(a){this.F=a},Oab=function(a,b,c){b&&(c?E4(a,b.map(function(d){return g.Xn(d,c)})):E4(a,b))},E4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.t(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.fz(m,f);d&&(e++,0!==d&&a.F.sendVideoStatsEngageEvent(d,f))},mbb=function(a){g.qR.call(this,a);
var b=this;this.loadNumber=0;this.I={};this.logger=new lbb(this.player);this.D=new g.MF(this);this.C=this.wp=null;this.events=new g.MF(this);this.J=this.j=null;this.T=[];g.D(this,this.D);this.D.S(this.player,"onVideoAreaChange",function(){b.ea("onVideoAreaChange")});
this.D.S(this.player,"onHideControls",function(){b.ea("onHideControls")});
this.D.S(this.player,"onShowControls",function(){b.ea("onShowControls")});
this.D.S(this.player,"resize",function(d){b.ea("resize",d)});
this.D.S(this.player,"presentingplayerstatechange",function(d){b.ea("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.PY,this);this.subscribe("resize",this.vG,this);this.player.V().ya.subscribe("vast_info_card_add",this.LV,this);g.D(this,this.events);this.Y=this.createElement({G:"div",N:"video-custom-annotations"});this.u=new g.U({G:"div",Ja:["ytp-player-content","ytp-iv-player-content"]});g.D(this,this.u);g.GQ(this.player,this.u.element,4);this.u.hide();this.B=new g.U({G:"div",Ja:["ytp-iv-video-content"]});g.D(this,this.B);a=this.createElement({G:"div",N:"video-annotations"});
a.appendChild(this.Y);this.B.element.appendChild(a);this.Yv()&&this.load();var c=this.createElement({G:"style"});(g.ye("HEAD")[0]||document.body).appendChild(c);g.eb(this,function(){g.Pe(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},nbb=function(a){a=a.createElement({G:"div",
Ja:["annotation","annotation-type-custom"]});g.Ml(a,!1);return a},obb=function(a,b){b=!b.isCued()&&!g.T(b,1024);
g.wN(a.u,b);g.wN(a.B,b)},pbb=function(a,b){for(var c={},d=g.t(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Ja(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(pbb(a,e))}return c},tbb=function(a){var b=a.player.getVideoData();
if(b.Sa){var c=a.player.V().ya.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.nw(h)&&h.responseXML?h.responseXML:null)&&qbb(a,h)}};
g.yx()&&(d.onFinish=rbb(a,d.onFinish));d.postParams={ic_only:"1"};sbb(d,c);g.uw(b.Sa,d)}}},sbb=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.KA&&(a.postParams.ic_coll=b.KA);b.DE&&(a.postParams.ic_xml=b.DE);b.BD&&(a.postParams.ic_track=b.BD)},ubb=function(a){var b=new g.U({G:"div"});
g.Ml(b.element,!1);var c=new Jab(a.player,b.element,F4(a));g.D(c,b);b.Da(a.u.element);c.mD();return c},F4=function(a){if(!a.J){var b=new cab(a);
g.D(a,b);var c=new g.Bj(a);g.D(a,c);a.J=new dbb(b,c,a.player.V(),a.player.getVideoData(),a.logger,a.player,a.Ii)}return a.J},qbb=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.qC();if(e){var f=g.pC();f&&g.$v(g.EDa)(void 0,e,f,[g.mC(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=pbb(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=l4(f.type,vbb),p=l4(f.style,wbb),q=sab(f.data),r=0!==q.length?JSON.parse(q):{};var w=f.action;f=yab;if(null==w)var x=null;else if(g.Ia(w)){l=[];for(var z=g.t(w),B=z.next();!B.done;B=z.next()){var E=f(B.value);
E&&l.push(E)}x=l}else{var G=f(w);x=G?[G]:[]}e=m&&n?new zab(m,n,p,x,r):null}else e=null}catch(V){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var F=nbb(f),K=null;switch(l.type){case "branding":if(f.player.V().Ld)break;f.u.element.appendChild(F);K=new D4(F,F4(f),l);break;case "promotion":g.GQ(f.player,F,4),K=new ebb(F,F4(f),l)}K&&K.mD();if(f=K)g.D(a,f),a.I[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.j||(a.j=ubb(a),g.D(a,a.j));if("card"===e.type){c=a.j;var P=e&&e.data&&e.data.card_type;
f=e.data;if(P)switch(l=f.tracking||{},l={OT:l.impression,click:l.click,close:l.close,kX:l.teaser_impression,xH:l.teaser_click},F=f.tracking_params||{},K=null,P){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Si:l,uo:F.card?g.mC(F.card):null,Vk:F.teaser?g.mC(F.teaser):null,Zf:F.icon?g.mC(F.icon):null,channelId:f.channel_id,
customMessage:f.custom_message?f.custom_message:null,dW:f.image_url,title:f.title,metaInfo:f.meta_info,url:n4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};w4(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Si:l,uo:F.card?g.mC(F.card):null,Vk:F.teaser?
g.mC(F.teaser):null,Zf:F.icon?g.mC(F.icon):null,yD:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:n4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};w4(c,e);break;case "productListing":f.signin_url&&(K=n4({target:"current",value:f.signin_url}));P=[];for(var Q=f.offers||[],Y=0;Y<Q.length;Y++)P.push(new Fab(g.qe(Q[Y].merchant),g.qe(Q[Y].price)));e={id:e.id,
timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Si:l,uo:F.card?g.mC(F.card):null,Vk:F.teaser?g.mC(F.teaser):null,Zf:F.icon?g.mC(F.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,IA:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:
null,url:n4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),Afb:K,zfb:f.signin_title?f.signin_title:void 0,yfb:f.signin_message?f.signin_message:void 0,offers:P,onClickCommand:null};w4(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Si:l,uo:F.card?g.mC(F.card):null,Vk:F.teaser?
g.mC(F.teaser):null,Zf:F.icon?g.mC(F.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,IA:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:n4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};w4(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,
startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Si:l,uo:F.card?g.mC(F.card):null,Vk:F.teaser?g.mC(F.teaser):null,Zf:F.icon?g.mC(F.icon):null,yD:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:n4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null},w4(c,e)}}else Kab(a.j,e);c=!0}}c&&
(X3(a.player),a.vG())},xbb=function(a,b){var c=!1;
a.j||(a.j=ubb(a),g.D(a,a.j));for(var d=g.t(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(Lab(a.j,e.cardRenderer),c=!0);c&&(c=a.j,d=b.headerText?g.SB(b.headerText):"",g.Se(c.Tb,d),c.T&&c.T.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ka=b.trackingParams?g.mC(b.trackingParams):null,c.J=b.closeButton.infoCardIconRenderer.trackingParams?g.mC(b.closeButton.infoCardIconRenderer.trackingParams):null,c.Zf=b.icon.infoCardIconRenderer.trackingParams?
g.mC(b.icon.infoCardIconRenderer.trackingParams):null,X3(a.player),a.vG())},ybb=function(a,b,c,d,e){if(!a.player.V().Ld){var f=[];
b.navigationEndpoint&&g.M(b.navigationEndpoint,z4)&&g.M(b.navigationEndpoint,z4).browseId&&f.push(new vab("openUrl","click",new tab("/channel/"+g.M(b.navigationEndpoint,z4).browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&g.M(b.subscribeButton,
g.jK)){d.channel_id=g.M(b.subscribeButton,g.jK).channelId;var l;b=g.M(b.subscribeButton,g.jK);h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.SB(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.SB(b.subscriberCountText))):(b.subscriberCountText&&(e=g.SB(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.SB(b.subscriberCountWithSubscribeText)));var m,n=(null==(m=g.M(null==(l=b.signInEndpoint)?void 0:l.commandMetadata,g.T2))?void 0:m.url)||"";l={subscribeText:g.SB(b.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.SB(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:n};d.standalone_subscribe_button_data=l}f=new zab(c,"branding","branding",f,d);l=nbb(a);a.u.element.appendChild(l);f=new D4(l,F4(a),f);f.mD();g.D(f,f);a.I[c]=f}},rbb=function(a,b){return function(){var c=g.wa.apply(0,arguments);
a.isDisposed()||a.T.push(g.$n.Ci(function(){b.apply(null,g.u(c))}))}},zbb=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.zQ.prototype.oz=g.ca(18,function(a,b){var c=g.IR(this.ub());c&&c.oz(a,b)});
var Z3={},$3=null;g.Sa(b4,g.yo);g.k=b4.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.u;else if(this.bd())return!1;a4(this);this.startTime=a=g.Ra();-1==this.j&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.rG();this.El("play");-1==this.j&&this.El("resume");this.j=1;var b=g.Oa(this);b in Z3||(Z3[b]=this);Y$a();Z$a(this,a);return!0};
g.k.stop=function(a){a4(this);this.j=0;a&&(this.progress=1);$$a(this,this.progress);this.El("stop");this.Aq()};
g.k.pause=function(){this.bd()&&(a4(this),this.j=-1,this.El("pause"))};
g.k.qa=function(){0==this.j||this.stop(!1);this.El("destroy");b4.If.qa.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.pI=function(){this.El("animate")};
g.k.El=function(a){this.dispatchEvent(new aab(a,this))};
g.Sa(aab,g.fb);g.Sa(c4,b4);c4.prototype.C=function(){};
c4.prototype.pI=function(){this.C();c4.If.pI.call(this)};
c4.prototype.Aq=function(){this.C();c4.If.Aq.call(this)};
c4.prototype.rG=function(){this.C();c4.If.rG.call(this)};
g.Sa(bab,c4);bab.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};var z4=new g.Lp("browseEndpoint");g.v(cab,g.C);g.k=cab.prototype;g.k.Qa=function(a,b,c,d){c=(0,g.Pa)(c,d||this.u);a=g.wz(a,b,c);this.j.push(a);return a};
g.k.VF=function(a,b,c,d){c=(0,g.Pa)(c,d||this.u);a=g.xqa(a,b,c);this.j.push(a);return a};
g.k.Fc=function(a){g.xz(a);g.qb(this.j,a)};
g.k.fg=function(){g.xz(this.j);this.j.length=0};
g.k.qa=function(){this.fg();g.C.prototype.qa.call(this)};g.v(fab,g.qR);g.k=fab.prototype;g.k.load=function(){g.qR.prototype.load.call(this);if(!f4(this)){var a=g.ZBa(this.player.getVideoData());a?(a=eab(a,gab(this)),g4(this,a,!1)):hab(this)}};
g.k.unload=function(){g4(this,null);this.B&&(this.B.abort(),this.B=null);g.qR.prototype.unload.call(this)};
g.k.yh=function(a,b){return f4(this)?"loadCustomEndscreenRenderer"===a?(a=eab(b,"new"),g4(this,a),!0):null:null};
g.k.getOptions=function(){return f4(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.Eb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<Abb.length;f++){var h=Math.abs(b.width-Abb[f]);if(-1===e||d>=h)e=f,d=h}d=Bbb[e];this.u&&g.ul(this.u.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.D[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.Kl(e.element,m,f);g.Al(e.element,n,p);this.ma&&(g.po(e.element,Cbb),256<m||256<f?g.mo(e.element,"ytp-ce-large-round"):96<m||96<f?g.mo(e.element,"ytp-ce-medium-round"):g.mo(e.element,"ytp-ce-small-round"));g.po(e.element,Dbb);m=h.left+h.width/2;h=h.top+l/2;g.mo(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":
.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.po(e.element,Bbb);g.mo(e.element,d);(e=g.ze(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.ul(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())k4(this,this.endscreen.impressionUrls),(a=g.qC())&&this.endscreen.visualElement&&g.AM(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.D[a];g.mo(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.mo(b,"ytp-ce-shown");k4(this,c.impressionUrls);(b=g.qC())&&g.AM(b,c.visualElement);this.player.V().I&&this.player.Na("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.oo(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.oo(b,"ytp-ce-shown");this.player.V().I&&this.player.Na("endscreenelementhidden",a)}};
g.k.R6=function(a){var b=this;a.target===window&&(new g.eo(function(){for(var c=g.t(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.po(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var Abb=[346,426,470,506,570,640,853,1280,1920],Bbb="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),Dbb=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],Cbb=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var uab={Epa:"current",wOa:"new"};var wab={CLOSE:"close",jSa:"openUrl",SUBSCRIBE:"subscribe"},xab={xka:"click",CLOSE:"close",Uza:"hidden",IXa:"rollOut",JXa:"rollOver",XZa:"shown"};zab.prototype.cf=function(){var a=Aab(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var wbb={Pfa:"anchored",nY:"branding",CHANNEL:"channel",tpa:"cta",Xza:"highlightText",eEa:"label",PLAYLIST:"playlist",bVa:"popup",I1a:"speech",SUBSCRIBE:"subscribe",P4a:"title",VIDEO:"video",Dab:"website"},vbb={nY:"branding",yia:"card",Nra:"drawer",Wza:"highlight",QJa:"marker",kWa:"promotion",TEXT:"text",icb:"widget"};g.v(r4,g.C);g.k=r4.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.IB(a,b,{id:c,namespace:"annotations_module"});d&&this.Ya.set(a,d);e&&this.eb.set(a,e);this.context.F.Se([a])};
g.k.mD=function(){this.context.u.subscribe("resize",this.xE,this)};
g.k.wb=function(){return this.element};
g.k.qI=function(a,b,c,d,e,f){if(this.xb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.Pe(this.wb())};
g.k.xE=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=m4(a);if(f){var h=Hab(f,a.target),l=function(){a.j&&e.context.F.pauseVideo();var m=e.context.videoData.D||!1,n=g.fw(f||"");m&&n&&(n.v||n.list)?e.context.F.Ln(n.v,b,n.list,!1):g.kL(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);E4(this.context.logger,c,l,d);Gab(f)||(c=g.qC(),d=b.itct,c&&d&&g.DM(c,g.mC(d)))}};
g.k.qa=function(){this.Ya.clear();this.eb.clear();g.C.prototype.qa.call(this)};
g.k.createElement=function(a){a=new g.U(a);g.D(this,a);return a.element};g.v(Jab,r4);g.k=Jab.prototype;g.k.zs=function(){this.oa&&w4(this,this.oa)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.F.getRootNode())?(a=g.Ll(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.xE=function(){var a=this.isAvailable();g.Ml(this.wb(),a);g.qo(this.context.F.getRootNode(),g.HW.IV_DRAWER_ENABLED,a);X3(this.F)};
g.k.destroy=function(){this.F.oz(!1);try{this.F.getRootNode().removeChild(this.C)}catch(a){}g.Rz(this.ma);g.xz(this.ya);this.Sa&&this.Sa.dispose();this.D&&this.D.dispose();r4.prototype.destroy.call(this)};
g.k.h1=function(){if(this.B){E4(this.context.logger,B4(this).Si.close);var a=g.qC();a&&this.J&&g.DM(a,this.J);v4(this)}};
g.k.B1=function(){g.qo(this.C,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.k.w3=function(){var a=g.qC(),b=B4(this);b=b?b.Zf:this.Zf;a&&b&&g.BM(a,[b])};
g.k.v3=function(){var a=g.qC(),b=B4(this);b=b?b.Zf:this.Zf;a&&b&&g.CM(a,[b])};
g.k.OY=function(){var a=B4(this);E4(this.context.logger,a.Si.kX);var b=g.qC();b&&a&&g.BM(b,[a.Vk,a.Zf])};
g.k.x3=function(){var a=g.qC(),b=B4(this);a&&b&&g.CM(a,[b.Vk])};
g.k.MY=function(a){var b=B4(this),c=g.qC();this.j?a?(a=this.context.logger,E4(a,b.Si.xH),a.F.sendVideoStatsEngageEvent(4,void 0),c&&b.Vk&&g.DM(c,b.Vk)):(a=this.context.logger,E4(a,b.Si.xH),a.F.sendVideoStatsEngageEvent(4,void 0),c&&b.Zf&&g.DM(c,b.Zf)):(a=this.context.logger,E4(a,b.Si.xH),a.F.sendVideoStatsEngageEvent(4,void 0),c&&this.Zf&&g.DM(c,this.Zf))};g.v(C4,r4);C4.prototype.mD=function(){r4.prototype.mD.call(this);Zab(this)};
C4.prototype.show=function(){r4.prototype.show.call(this);var a=g.qC(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.BM(a,[g.mC(b.itct)])};
C4.prototype.hide=function(){r4.prototype.hide.call(this);var a=g.qC(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.CM(a,[g.mC(b.itct)])};g.v(D4,C4);
D4.prototype.show=function(){if(!this.isActive){C4.prototype.show.call(this);if(!this.J){g.mo(this.wb(),"iv-branding");var a=this.annotation.data;this.u=this.createElement({G:"img",Ja:["branding-img","iv-click-target"],X:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.Ml(this.u,!1);var b=this.createElement({G:"button",Ja:["branding-img-container","ytp-button"]});b.appendChild(this.u);this.wb().appendChild(b);var c=this.annotation.cf();c&&s4(this,b,
c,this.annotation.id,a.session_data);cbb(this,a);this.J=!0}g.Ml(this.wb(),!0);this.isActive=!0;this.u&&($ab(this,this.u),g.mo(this.context.F.getRootNode(),"ytp-branding-shown"))}};
D4.prototype.hide=function(){this.isActive&&(C4.prototype.hide.call(this),g.Ml(this.wb(),!1),this.isActive=!1,g.oo(this.context.F.getRootNode(),"ytp-branding-shown"))};
D4.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);C4.prototype.destroy.call(this)};g.v(ebb,C4);g.k=ebb.prototype;g.k.show=function(){this.isActive||(C4.prototype.show.call(this),this.Y||(gbb(this),this.Y=!0),g.Ml(this.wb(),!0),g.uf(function(){g.oo(this.wb(),"iv-promo-inactive")},100,this),this.wb().removeAttribute("aria-hidden"),this.isActive=!0,kbb(this),hbb(this),ibb(this,this.I))};
g.k.hide=function(){this.isActive&&(g.mo(this.wb(),"iv-promo-inactive"),this.isActive=!1,this.wb().setAttribute("aria-hidden","true"))};
g.k.qI=function(a,b,c,d,e,f){return this.isCollapsed?!1:C4.prototype.qI.call(this,a,b,c,d,e,f)};
g.k.A2=function(a){this.T=!0;fbb(this,500,a)};
g.k.z2=function(){this.T=!1;jbb(this)};
g.k.s2=function(a){a.stopPropagation();this.hide()};
g.k.t2=function(a){a.stopPropagation();kbb(this);this.isCollapsed=!0;g.mo(this.wb(),"iv-promo-collapsed-no-delay");this.D.start()};
g.k.destroy=function(){this.D.dispose();C4.prototype.destroy.call(this)};g.v(mbb,g.qR);g.k=mbb.prototype;g.k.yh=function(a,b){if(!zbb(this.player.V().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.v5a(b))&&qbb(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(Nab(this.j,b),X3(this.player)),!0}return null};
g.k.getOptions=function(){return zbb(this.player.V().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Yv=function(){var a=this.player.V(),b=this.player.getVideoData(),c=a.annotationsLoadPolicy||b.annotationsLoadPolicy;return b.D&&a.ma||a.K("embeds_enable_muted_autoplay")&&this.player.isMutedByMutedAutoplay()?!1:1===c&&!b.ZQ||a.ya.get(b.videoId)||g.qK(b)||g.rK(b)?!0:!1};
g.k.vG=function(){if(this.B){var a=this.player.ib().getVideoContentRect(!0);g.Kl(this.B.element,a.width,a.height);g.Al(this.B.element,a.left,a.top)}if(this.j){var b=this.player.zk();a=this.j;b=b.width;g.qo(a.C,"iv-drawer-small",426>=b);g.qo(a.C,"iv-drawer-big",1280<=b)}};
g.k.PY=function(a){obb(this,a.state);g.T(a.state,2)&&(this.zj()&&this.qo()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.oz(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.C=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.nw(h)&&h.responseXML?h.responseXML:null)&&(qbb(b,h),g.mo(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.qR.prototype.load.call(this);obb(this,this.player.Gb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.yx()&&(a=rbb(this,a));var e={format:"XML",onFinish:a,onError:function(){b.C=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.V().ya.get(d);f&&sbb(e,f);f=f&&(f.DE||f.KA);if(!c.xw||f)c.Sa?this.C=g.uw(c.Sa,e):(this.wp=function(){b.onVideoDataChange(e)},this.player.addEventListener("videodatachange",this.wp));
g.GQ(this.player,this.B.element,4);this.vG();(f=g.qK(c))&&xbb(this,f);(f=g.rK(c))&&f.featuredChannel&&ybb(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Sa&&(this.wp&&(this.player.removeEventListener("videodatachange",this.wp),this.wp=null),this.C=g.uw(b.Sa,a))};
g.k.unload=function(){this.player.Rf("annotations_module");for(var a=g.t(Object.keys(this.I)),b=a.next();!b.done;b=a.next())this.I[b.value].destroy();this.J=null;this.j&&(this.j.destroy(),this.j=null,X3(this.player));this.C&&(this.C.abort(),this.C=null);this.I={};this.u.hide();g.qR.prototype.unload.call(this);this.B.detach();this.wp&&(this.player.removeEventListener("videodatachange",this.wp),this.wp=null)};
g.k.LV=function(a){a===this.player.getVideoData().videoId&&(this.loaded?tbb(this):this.load())};
g.k.zj=function(){return!!this.j&&this.j.isAvailable()};
g.k.qo=function(){return!!this.j&&this.j.B};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.zj();this.j&&(a?c?u4(this.j,c,b):u4(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):v4(this.j))};
g.k.oz=function(a,b){this.player.ea(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.qa=function(){this.player.V().ya.unsubscribe("vast_info_card_add",this.LV,this);g.oo(this.player.getRootNode(),g.HW.IV_DRAWER_OPEN);for(var a=this.T,b=g.$n,c=0,d=a.length;c<d;c++)b.Dm(a[c]);this.T.length=0;g.qR.prototype.qa.call(this)};
g.k.createElement=function(a){a=new g.U(a);g.D(this,a);return a.element};g.pR("annotations_module",mbb);g.pR("creatorendscreen",fab);})(_yt_player);
