(function(g){var window=this;'use strict';var Edb=function(a,b){a.Na("onAutonavCoundownStarted",b)},C5=function(a,b,c){g.qo(a.element,"ytp-suggestion-set",!!b.videoId);
var d=b.playlistId;c=b.qg(c?c:"mqdefault.jpg");var e=null,f=null;b instanceof g.iJ&&(b.lengthText?(e=b.lengthText||null,f=b.hv||null):b.lengthSeconds&&(e=g.yO(b.lengthSeconds),f=g.yO(b.lengthSeconds,!0)));var h=!!d;d=h&&"RD"===g.gJ(d).type;var l=b instanceof g.iJ?b.isLivePlayback:null,m=b instanceof g.iJ?b.isUpcoming:null,n=b.author,p=b.shortViewCount,q=b.publishedTimeText,r=[],w=[];n&&r.push(n);p&&(r.push(p),w.push(p));q&&w.push(q);c={title:b.title,author:n,author_and_views:r.join(" \u2022 "),aria_label:b.ariaLabel||
g.OL("Watch $TITLE",{TITLE:b.title}),duration:e,timestamp:f,url:b.Jo(),is_live:l,is_upcoming:m,is_list:h,is_mix:d,background:c?"background-image: url("+c+")":"",views_and_publish_time:w.join(" \u2022 "),autoplayAlternativeHeader:b.yr};b instanceof g.hJ&&(c.playlist_length=b.playlistLength);a.update(c)},D5=function(a){var b=a.V(),c=b.C;
g.U.call(this,{G:"a",N:"ytp-autonav-suggestion-card",X:{href:"{{url}}",target:c?b.Y:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},W:[{G:"div",Ja:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],X:{style:"{{background}}"},W:[{G:"div",X:{"aria-label":"{{timestamp}}"},Ja:["ytp-autonav-timestamp"],ra:"{{duration}}"},{G:"div",Ja:["ytp-autonav-live-stamp"],ra:"Live"},{G:"div",
Ja:["ytp-autonav-upcoming-stamp"],ra:"Upcoming"},{G:"div",N:"ytp-autonav-list-overlay",W:[{G:"div",N:"ytp-autonav-mix-text",ra:"Mix"},{G:"div",N:"ytp-autonav-mix-icon"}]}]},{G:"div",Ja:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],ra:"{{title}}"},{G:"div",Ja:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],ra:"{{author}}"},{G:"div",Ja:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],ra:"{{views_and_publish_time}}"}]});this.F=a;this.suggestion=
null;this.j=c;this.Qa("click",this.onClick);this.Qa("keypress",this.onKeyPress)},E5=function(a,b){b=void 0===b?!1:b;
g.U.call(this,{G:"div",N:"ytp-autonav-endscreen-countdown-overlay"});var c=this;this.I=b;this.D=void 0;this.B=0;this.container=new g.U({G:"div",N:"ytp-autonav-endscreen-countdown-container"});g.D(this,this.container);this.container.Da(this.element);b=a.V();var d=b.C;this.F=a;this.suggestion=null;this.onVideoDataChange("newdata",this.F.getVideoData());this.S(a,"videodatachange",this.onVideoDataChange);var e=["ytp-autonav-endscreen-upnext-thumbnail"];b.K("web_rounded_thumbnails")&&e.push("rounded-thumbnail");
this.j=new g.U({G:"div",N:"ytp-autonav-endscreen-upnext-container",X:{"aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},W:[{G:"div",N:"ytp-autonav-endscreen-upnext-header"},{G:"div",N:"ytp-autonav-endscreen-upnext-alternative-header",ra:"{{autoplayAlternativeHeader}}"},{G:"a",N:"ytp-autonav-endscreen-link-container",X:{href:"{{url}}",target:d?b.Y:""},W:[{G:"div",Ja:e,X:{style:"{{background}}"},W:[{G:"div",
X:{"aria-label":"{{timestamp}}"},Ja:["ytp-autonav-timestamp"],ra:"{{duration}}"},{G:"div",Ja:["ytp-autonav-live-stamp"],ra:"Live"},{G:"div",Ja:["ytp-autonav-upcoming-stamp"],ra:"Upcoming"}]},{G:"div",N:"ytp-autonav-endscreen-video-info",W:[{G:"div",N:"ytp-autonav-endscreen-premium-badge"},{G:"div",N:"ytp-autonav-endscreen-upnext-title",ra:"{{title}}"},{G:"div",N:"ytp-autonav-endscreen-upnext-author",ra:"{{author}}"},{G:"div",N:"ytp-autonav-view-and-date",ra:"{{views_and_publish_time}}"},{G:"div",
N:"ytp-autonav-author-and-view",ra:"{{author_and_views}}"}]}]}]});g.D(this,this.j);this.j.Da(this.container.element);d||this.S(this.j.Ba("ytp-autonav-endscreen-link-container"),"click",this.MP);this.F.sb(this.container.element,this,115127);this.F.sb(this.j.Ba("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.U({G:"div",N:"ytp-autonav-overlay"});g.D(this,this.overlay);this.overlay.Da(this.container.element);this.u=new g.U({G:"div",N:"ytp-autonav-endscreen-button-container"});
g.D(this,this.u);this.u.Da(this.container.element);this.cancelButton=new g.U({G:"button",Ja:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",b.K("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],X:{"aria-label":"Cancel autoplay"},ra:"Cancel"});g.D(this,this.cancelButton);this.cancelButton.Da(this.u.element);this.cancelButton.Qa("click",this.WY,this);this.F.sb(this.cancelButton.element,this,115129);this.playButton=new g.U({G:"a",Ja:["ytp-autonav-endscreen-upnext-button",
"ytp-autonav-endscreen-upnext-play-button",b.K("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],X:{href:"{{url}}",role:"button","aria-label":"Play next video"},ra:"Play Now"});g.D(this,this.playButton);this.playButton.Da(this.u.element);this.playButton.Qa("click",this.MP,this);this.F.sb(this.playButton.element,this,115130);this.C=new g.eo(function(){Fdb(c)},500);
g.D(this,this.C);this.LP();this.S(a,"autonavvisibility",this.LP);this.F.K("web_autonav_color_transition")&&(this.S(a,"autonavchange",this.VY),this.S(a,"onAutonavCoundownStarted",this.z4))},F5=function(a){var b=a.F.zk(!0,a.F.isFullscreen());
g.qo(a.container.element,"ytp-autonav-endscreen-small-mode",a.lh(b));g.qo(a.container.element,"ytp-autonav-endscreen-is-premium",!!a.suggestion&&!!a.suggestion.uH);g.qo(a.F.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!a.F.Qf());g.qo(a.F.getRootNode(),"countdown-running",a.Ek());g.qo(a.container.element,"ytp-player-content",a.F.Qf());g.ul(a.overlay.element,{width:b.width+"px"});if(!a.Ek()){a.F.Qf()?Gdb(a,Math.round(Hdb(a)/1E3)):Gdb(a);b=!!a.suggestion&&!!a.suggestion.yr;var c=a.F.Qf()||!b;
g.qo(a.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!c&&b);g.qo(a.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",c&&!b);g.wN(a.u,a.F.Qf());g.qo(a.element,"ytp-enable-w2w-color-transitions",Idb(a))}},Fdb=function(a){var b=Hdb(a),c=Math,d=c.min;
var e=a.B?Date.now()-a.B:0;c=d.call(c,e,b);Gdb(a,Math.ceil((b-c)/1E3));500>=b-c&&a.Ek()?a.select(!0):a.Ek()&&a.C.start()},Hdb=function(a){if(a.F.isFullscreen()){var b;
a=null==(b=a.F.getVideoData())?void 0:b.yw;return-1===a||void 0===a?8E3:a}return 0<=a.F.Rr()?a.F.Rr():g.NG(a.F.V().experiments,"autoplay_time")||1E4},Idb=function(a){var b;
return!(null==(b=a.F.getVideoData())||!b.watchToWatchTransitionRenderer)},Gdb=function(a,b){b=void 0===b?-1:b;
a=a.j.Ba("ytp-autonav-endscreen-upnext-header");g.Ne(a);if(0<=b){b=String(b);var c="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],d="Up next in $SECONDS".indexOf(c);if(0<=d){a.appendChild(g.Le("Up next in $SECONDS".slice(0,d)));var e=g.Ke("span");g.ko(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.Se(e,b);a.appendChild(e);a.appendChild(g.Le("Up next in $SECONDS".slice(d+c.length)));return}}g.Se(a,"Up next")},G5=function(a,b){g.U.call(this,{G:"div",
Ja:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},H5=function(a){g.U.call(this,{G:"div",
Ja:["ytp-upnext","ytp-player-content"],X:{"aria-label":"{{aria_label}}"},W:[{G:"div",N:"ytp-cued-thumbnail-overlay-image",X:{style:"{{background}}"}},{G:"span",N:"ytp-upnext-top",W:[{G:"span",N:"ytp-upnext-header",ra:"Up Next"},{G:"span",N:"ytp-upnext-title",ra:"{{title}}"},{G:"span",N:"ytp-upnext-author",ra:"{{author}}"}]},{G:"a",N:"ytp-upnext-autoplay-icon",X:{role:"button",href:"{{url}}","aria-label":"Play next video"},W:[{G:"svg",X:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
W:[{G:"circle",N:"ytp-svg-autoplay-circle",X:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{G:"circle",N:"ytp-svg-autoplay-ring",X:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{G:"path",N:"ytp-svg-fill",X:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{G:"span",N:"ytp-upnext-bottom",W:[{G:"span",N:"ytp-upnext-cancel"},{G:"span",N:"ytp-upnext-paused",
ra:"Autoplay is paused"}]}]});this.api=a;this.cancelButton=null;this.D=this.Ba("ytp-svg-autoplay-ring");this.B=this.notification=this.j=this.suggestion=null;this.C=new g.eo(this.IE,5E3,this);this.u=0;var b=this.Ba("ytp-upnext-cancel");this.cancelButton=new g.U({G:"button",Ja:["ytp-upnext-cancel-button","ytp-button"],X:{tabindex:"0","aria-label":"Cancel autoplay"},ra:"Cancel"});g.D(this,this.cancelButton);this.cancelButton.Qa("click",this.XY,this);this.cancelButton.Da(b);this.cancelButton&&this.api.sb(this.cancelButton.element,
this,115129);g.D(this,this.C);this.api.sb(this.element,this,18788);b=this.Ba("ytp-upnext-autoplay-icon");this.S(b,"click",this.YY);this.api.sb(b,this,115130);this.NP();this.S(a,"autonavvisibility",this.NP);this.S(a,"mdxnowautoplaying",this.j5);this.S(a,"mdxautoplaycanceled",this.k5);g.qo(this.element,"ytp-upnext-mobile",this.api.V().u)},Jdb=function(a,b){if(b)return b;
if(a.api.isFullscreen()){var c;a=null==(c=a.api.getVideoData())?void 0:c.yw;return-1===a||void 0===a?8E3:a}return 0<=a.api.Rr()?a.api.Rr():g.NG(a.api.V().experiments,"autoplay_time")||1E4},Kdb=function(a,b){b=Jdb(a,b);
var c=Math,d=c.min;var e=(0,g.N)()-a.u;c=d.call(c,e,b);b=0===b?1:Math.min(c/b,1);a.D.setAttribute("stroke-dashoffset",""+-211*(b+1));1<=b&&a.Ek()&&3!==a.api.getPresentingPlayerType()?a.select(!0):a.Ek()&&a.j.start()},I5=function(a){G5.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.U({G:"div",N:"ytp-suggestion-panel",W:[{G:"div",Ja:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],ra:"More videos"}]});this.J=new g.U({G:"div",N:"ytp-suggestions-container"});this.videos=[];this.B=null;this.D=this.I=!1;this.u=new E5(this.player);g.D(this,this.u);this.u.Da(this.element);a.getVideoData().jc?this.j=this.u:(this.j=new H5(a),g.GQ(this.player,this.j.element,4),g.D(this,this.j));this.overlay=new g.U({G:"div",
N:"ytp-autonav-overlay-cancelled-state"});g.D(this,this.overlay);this.overlay.Da(this.element);this.C=new g.MF(this);g.D(this,this.C);g.D(this,this.table);this.table.Da(this.element);this.table.show();g.D(this,this.J);this.J.Da(this.table.element);this.hide()},J5=function(a){var b=a.Qf();
b!==a.D&&(a.D=b,a.player.ea("autonavvisibility"),a.D?(a.u!==a.j&&a.u.hide(),a.table.hide()):(a.u!==a.j&&a.u.show(),a.table.show()))},K5=function(a,b){g.U.call(this,{G:"button",
Ja:["ytp-watch-on-youtube-button","ytp-button"],ra:"{{content}}"});this.F=a;this.buttonType=this.buttonType=b;b=this.F.getVideoData();if(a.K("embeds_enable_server_driven_watch_again_on_youtube")){var c,d;if(c=(a=null==(c=b.pd)?void 0:null==(d=c.playerOverlays)?void 0:d.playerOverlayRenderer)&&g.M(a.watchOnYoutubeButton,g.EKa))this.j=c}if(this.j)this.update({content:this.j.title}),this.F.Pg(this.element,this),this.F.Kh(this.element,this.j.trackingParams||null);else{switch(this.buttonType){case 1:c=
"Watch again on YouTube";d=156915;break;case 2:c="Continue watching on YouTube";d=156942;break;default:c="Continue watching on YouTube",d=156942}this.update({content:c});this.F.sb(this.element,this,d)}2===this.buttonType&&g.mo(this.element,"ytp-continue-watching-button");this.Qa("click",this.onClick);g.wN(this,!0)},L5=function(a,b){G5.call(this,a,"embeds-lite-endscreen");
this.F=a;this.j=b;this.F.sb(this.element,this,156943);this.watchButton=new K5(a,2);g.D(this,this.watchButton);this.watchButton.Da(this.element);this.hide()},Ldb=function(a){G5.call(this,a,"subscribecard-endscreen");
this.j=new g.U({G:"div",N:"ytp-subscribe-card",W:[{G:"img",N:"ytp-author-image",X:{src:"{{profilePicture}}"}},{G:"div",N:"ytp-subscribe-card-right",W:[{G:"div",N:"ytp-author-name",ra:"{{author}}"},{G:"div",N:"html5-subscribe-button-container"}]}]});g.D(this,this.j);this.j.Da(this.element);var b=a.getVideoData();this.subscribeButton=new g.uS("Subscribe",null,"Unsubscribe",null,!0,!1,b.Zl,b.subscribed,"trailer-endscreen",null,null,a);g.D(this,this.subscribeButton);this.subscribeButton.Da(this.j.Ba("html5-subscribe-button-container"));
this.S(a,"videodatachange",this.La);this.La();this.hide()},M5=function(a){var b=a.V(),c=g.PF||g.IH?{style:"will-change: opacity"}:void 0,d=b.C,e=["ytp-videowall-still"];
b.u&&e.push("ytp-videowall-show-text");g.U.call(this,{G:"a",Ja:e,X:{href:"{{url}}",target:d?b.Y:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},W:[{G:"div",N:"ytp-videowall-still-image",X:{style:"{{background}}"}},{G:"span",N:"ytp-videowall-still-info",X:{"aria-hidden":"true"},W:[{G:"span",N:"ytp-videowall-still-info-bg",W:[{G:"span",N:"ytp-videowall-still-info-content",X:c,W:[{G:"span",N:"ytp-videowall-still-info-title",ra:"{{title}}"},
{G:"span",N:"ytp-videowall-still-info-author",ra:"{{author_and_views}}"},{G:"span",N:"ytp-videowall-still-info-live",ra:"Live"},{G:"span",N:"ytp-videowall-still-info-duration",ra:"{{duration}}"}]}]}]},{G:"span",Ja:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],X:{"aria-hidden":"true"},W:[{G:"span",N:"ytp-videowall-still-listlabel-icon"},"Playlist",{G:"span",N:"ytp-videowall-still-listlabel-length",W:[" (",{G:"span",ra:"{{playlist_length}}"},")"]}]},{G:"span",Ja:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],X:{"aria-hidden":"true"},W:[{G:"span",N:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{G:"span",N:"ytp-videowall-still-listlabel-length",ra:" (50+)"}]}]});this.suggestion=null;this.u=d;this.api=a;this.j=new g.MF(this);g.D(this,this.j);this.Qa("click",this.onClick);this.Qa("keypress",this.onKeyPress);this.j.S(a,"videodatachange",this.onVideoDataChange);a.Pg(this.element,this);this.onVideoDataChange()},N5=function(a){G5.call(this,a,"videowall-endscreen");
var b=this;this.F=a;this.B=0;this.stills=[];this.C=this.videoData=null;this.D=this.J=!1;this.T=null;this.u=new g.MF(this);g.D(this,this.u);this.Y=a.K("web_rounded_thumbnails");this.I=new g.eo(function(){g.mo(b.element,"ytp-show-tiles")},0);
g.D(this,this.I);var c=new g.U({G:"button",Ja:["ytp-button","ytp-endscreen-previous"],X:{"aria-label":"Previous"},W:[g.BN()]});g.D(this,c);c.Da(this.element);c.Qa("click",this.cZ,this);this.table=new g.tN({G:"div",N:"ytp-endscreen-content"});g.D(this,this.table);this.table.Da(this.element);c=new g.U({G:"button",Ja:["ytp-button","ytp-endscreen-next"],X:{"aria-label":"Next"},W:[g.CN()]});g.D(this,c);c.Da(this.element);c.Qa("click",this.bZ,this);a.getVideoData().jc?this.j=new E5(a,!0):this.j=new H5(a);
g.D(this,this.j);g.GQ(this.player,this.j.element,4);a.sb(this.element,this,158789);this.hide()},O5=function(a){return g.HQ(a.player)&&a.DA()&&!a.C},Mdb=function(a){var b,c,d,e;
return(null==(b=a.videoData)?0:null==(c=b.suggestions)?0:c.length)?null==(d=a.videoData)?void 0:d.suggestions:[null==(e=a.videoData)?void 0:g.kJ(e)]},P5=function(a){var b=a.Qf();
b!==a.J&&(a.J=b,a.player.ea("autonavvisibility"))},Q5=function(a){G5.call(this,a,"watch-again-on-youtube-endscreen");
this.watchButton=new K5(a,1);g.D(this,this.watchButton);this.watchButton.Da(this.element);g.w5a(a)&&(this.j=new g.y2(a,g.oQ(a)),g.D(this,this.j),this.u=new g.U({G:"div",Ja:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],X:{tabIndex:"-1"},W:[this.j]}),g.D(this,this.u),this.j.Da(this.u.element),this.u.Da(this.element));a.sb(this.element,this,156914);this.hide()},Qdb=function(a){g.qR.call(this,a);
var b=this;this.endScreen=null;this.u=this.j=this.B=this.C=!1;this.listeners=new g.MF(this);g.D(this,this.listeners);var c=a.V(),d=a.getVideoData();d=d&&0!==d.endSeconds;if(g.cx(g.bI(c))&&d&&!g.DQ(a))this.u=!0,this.endScreen=new L5(a,g.oQ(a));else{var e;(null==(e=g.oQ(a))?0:e.td())?this.endScreen=new Q5(a):Ndb(a)?(this.C=!0,Odb(this),this.j?this.endScreen=new I5(a):this.endScreen=new N5(a)):c.dh?this.endScreen=new Ldb(a):this.endScreen=new G5(a)}g.D(this,this.endScreen);g.GQ(a,this.endScreen.element,
4);Pdb(this);this.listeners.S(a,"videodatachange",this.onVideoDataChange,this);this.listeners.S(a,g.KB("endscreen"),function(f){b.onCueRangeEnter(f)});
this.listeners.S(a,g.LB("endscreen"),function(f){b.onCueRangeExit(f)})},Odb=function(a){var b=a.player.getVideoData();
if(!b||a.j===b.me&&a.B===b.jc)return!1;a.j=b.me;a.B=b.jc;return!0},Ndb=function(a){a=a.V();
return a.Dd&&!a.dh},Pdb=function(a){a.player.Rf("endscreen");
var b=a.player.getVideoData();b=new g.IB(Math.max(1E3*(b.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.IB(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});a.player.Se([b,c])};
g.BV.prototype.qz=g.ca(36,function(a){this.pN!==a&&(this.pN=a,this.Zk())});
g.kT.prototype.Pq=g.ca(35,function(a){this.u!==a&&(this.u=a,this.La())});
g.BV.prototype.Pq=g.ca(34,function(a){this.shareButton&&this.shareButton.Pq(a)});
g.$S.prototype.Oq=g.ca(33,function(a){this.u!==a&&(this.u=a,this.La())});
g.BV.prototype.Oq=g.ca(32,function(a){this.overflowButton&&this.overflowButton.Oq(a)});
g.gS.prototype.lD=g.ca(31,function(a){this.qN!==a&&(this.qN=a,this.tp())});
g.zQ.prototype.Rr=g.ca(5,function(){return this.app.Rr()});
g.pZ.prototype.Rr=g.ca(4,function(){return this.getVideoData().aI});g.v(D5,g.U);D5.prototype.select=function(){this.F.Ln(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.YA||void 0)&&this.F.vb(this.element)};
D5.prototype.onClick=function(a){g.RR(a,this.F,this.j,this.suggestion.sessionData||void 0)&&this.select()};
D5.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.Dz(a)||(this.select(),g.Cz(a))}};g.v(E5,g.U);g.k=E5.prototype;g.k.VD=function(a){this.suggestion!==a&&(this.suggestion=a,C5(this.j,a),this.playButton.updateValue("url",this.suggestion.Jo()),F5(this))};
g.k.Ek=function(){return 0<this.B};
g.k.zz=function(){this.Ek()||(this.B=Date.now(),Fdb(this),Edb(this.F,Hdb(this)),g.qo(this.F.getRootNode(),"countdown-running",this.Ek()))};
g.k.Hv=function(){this.Sq();Fdb(this);var a=this.j.Ba("ytp-autonav-endscreen-upnext-header");a&&g.Se(a,"Up next")};
g.k.Sq=function(){this.Ek()&&(this.C.stop(),this.B=0)};
g.k.select=function(a){this.F.nextVideo(!1,void 0===a?!1:a);this.Sq()};
g.k.MP=function(a){g.RR(a,this.F)&&(a.currentTarget===this.playButton.element?this.F.vb(this.playButton.element):a.currentTarget===this.j.Ba("ytp-autonav-endscreen-link-container")&&(a=this.j.Ba("ytp-autonav-endscreen-link-container"),this.F.Va(a,!0),this.F.vb(a)),this.select())};
g.k.WY=function(){this.F.vb(this.cancelButton.element);g.BQ(this.F,!0);this.D&&this.F.Na("innertubeCommand",this.D)};
g.k.onVideoDataChange=function(a,b){var c;this.D=null==(c=b.gR)?void 0:c.command};
g.k.z4=function(a){if(Idb(this)){var b=this.F.getVideoData().watchToWatchTransitionRenderer,c=null==b?void 0:b.fromColorPaletteDark;b=null==b?void 0:b.toColorPaletteDark;if(c&&b){var d=this.element;d.style.setProperty("--w2w-start-background-color",g.JO(c.surgeColor));d.style.setProperty("--w2w-start-primary-text-color",g.JO(c.primaryTitleColor));d.style.setProperty("--w2w-start-secondary-text-color",g.JO(c.secondaryTitleColor));d.style.setProperty("--w2w-end-background-color",g.JO(b.surgeColor));
d.style.setProperty("--w2w-end-primary-text-color",g.JO(b.primaryTitleColor));d.style.setProperty("--w2w-end-secondary-text-color",g.JO(b.secondaryTitleColor));d.style.setProperty("--w2w-animation-duration",a+"ms")}g.qo(this.element,"ytp-w2w-animate",!0)}};
g.k.VY=function(a){this.F.K("web_autonav_color_transition")&&2!==a&&g.qo(this.element,"ytp-w2w-animate",!1)};
g.k.LP=function(){var a=this.F.Qf();this.I&&this.tb!==a&&g.wN(this,a);F5(this);this.F.Va(this.container.element,a);this.F.Va(this.cancelButton.element,a);this.F.Va(this.j.Ba("ytp-autonav-endscreen-link-container"),a);this.F.Va(this.playButton.element,a)};
g.k.lh=function(a){return 400>a.width||459>a.height};g.v(G5,g.U);g.k=G5.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.DA=function(){return!1};
g.k.Qf=function(){return!1};
g.k.jU=function(){return!1};g.v(H5,g.U);g.k=H5.prototype;g.k.IE=function(){this.notification&&(this.C.stop(),this.Fc(this.B),this.B=null,this.notification.close(),this.notification=null)};
g.k.VD=function(a){this.suggestion=a;C5(this,a,"hqdefault.jpg")};
g.k.NP=function(){g.wN(this,this.api.Qf());this.api.Va(this.element,this.api.Qf());this.api.Va(this.Ba("ytp-upnext-autoplay-icon"),this.api.Qf());this.cancelButton&&this.api.Va(this.cancelButton.element,this.api.Qf())};
g.k.s5=function(){window.focus();this.IE()};
g.k.zz=function(a){var b=this;this.Ek()||(g.Sz("a11y-announce","Up Next "+this.suggestion.title),this.u=(0,g.N)(),this.j=new g.eo(function(){Kdb(b,a)},25),Kdb(this,a),Edb(this.api,Jdb(this,a)));
g.oo(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.U.prototype.hide.call(this)};
g.k.Ek=function(){return!!this.j};
g.k.Hv=function(){this.Sq();this.u=(0,g.N)();Kdb(this);g.mo(this.element,"ytp-upnext-autoplay-paused")};
g.k.Sq=function(){this.Ek()&&(this.j.dispose(),this.j=null)};
g.k.select=function(a){a=void 0===a?!1:a;if(this.api.V().K("autonav_notifications")&&a&&window.Notification&&"function"===typeof document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(this.IE(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.qg()}),this.B=this.S(this.notification,"click",this.s5),this.C.start())}this.Sq();this.api.nextVideo(!1,a)};
g.k.YY=function(a){!g.Re(this.cancelButton.element,g.yz(a))&&g.RR(a,this.api)&&(this.api.Qf()&&this.api.vb(this.Ba("ytp-upnext-autoplay-icon")),this.select())};
g.k.XY=function(){this.api.Qf()&&this.cancelButton&&this.api.vb(this.cancelButton.element);g.BQ(this.api,!0)};
g.k.j5=function(a){this.api.getPresentingPlayerType();this.show();this.zz(a)};
g.k.k5=function(){this.api.getPresentingPlayerType();this.Sq();this.hide()};
g.k.qa=function(){this.Sq();this.IE();g.U.prototype.qa.call(this)};g.v(I5,G5);g.k=I5.prototype;g.k.create=function(){G5.prototype.create.call(this);this.C.S(this.player,"appresize",this.fA);this.C.S(this.player,"onVideoAreaChange",this.fA);this.C.S(this.player,"videodatachange",this.onVideoDataChange);this.C.S(this.player,"autonavchange",this.OP);this.C.S(this.player,"autonavcancel",this.ZY);this.onVideoDataChange()};
g.k.show=function(){G5.prototype.show.call(this);(this.I||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.BQ(this.player,!1);g.HQ(this.player)&&this.DA()&&!this.B?(J5(this),2===this.videoData.autonavState?this.player.V().K("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.j.select(!0):this.j.zz():3===this.videoData.autonavState&&this.j.Hv()):(g.BQ(this.player,!0),J5(this));this.fA()};
g.k.hide=function(){G5.prototype.hide.call(this);this.j.Hv();J5(this)};
g.k.fA=function(){var a=this.player.zk(!0,this.player.isFullscreen());J5(this);F5(this.u);g.qo(this.element,"ytp-autonav-cancelled-small-mode",this.lh(a));g.qo(this.element,"ytp-autonav-cancelled-tiny-mode",this.QF(a));g.qo(this.element,"ytp-autonav-cancelled-mini-mode",400>=a.width||360>=a.height);this.overlay&&g.ul(this.overlay.element,{width:a.width+"px"});if(!this.D)for(a=0;a<this.videos.length;a++)g.qo(this.videos[a].element,"ytp-suggestion-card-with-margin",1===a%2)};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((a=this.videoData.suggestions)&&a.length){var b=g.kJ(this.videoData);b&&(this.j.VD(b),this.j!==this.u&&this.u.VD(b));for(b=0;b<Rdb.length;++b){var c=Rdb[b];if(a&&a[c]){this.videos[b]=new D5(this.player);var d=this.videos[b];c=a[c];d.suggestion!==c&&(d.suggestion=c,C5(d,c));g.D(this,this.videos[b]);this.videos[b].Da(this.J.element)}}}this.fA()}};
g.k.OP=function(a){1===a?(this.I=!1,this.B=this.videoData.clientPlaybackNonce,this.j.Sq(),this.tb&&this.fA()):(this.I=!0,this.Qf()&&(2===a?this.j.zz():3===a&&this.j.Hv()))};
g.k.ZY=function(a){a?this.OP(1):(this.B=null,this.I=!1)};
g.k.DA=function(){return 1!==this.videoData.autonavState};
g.k.lh=function(a){return(910>a.width||459>a.height)&&!this.QF(a)&&!(400>=a.width||360>=a.height)};
g.k.QF=function(a){return 800>a.width&&!(400>=a.width||360>=a.height)};
g.k.Qf=function(){return this.tb&&g.HQ(this.player)&&this.DA()&&!this.B};
var Rdb=[1,3,2,4];g.v(K5,g.U);g.k=K5.prototype;g.k.onClick=function(a){this.j?this.F.Na("innertubeCommand",this.j.onTap):g.SR(this.getVideoUrl(),this.F,a);this.F.vb(this.element)};
g.k.getVideoUrl=function(){var a=!0;switch(this.buttonType){case 1:a=!0;break;case 2:a=!1}a=this.F.getVideoUrl(a,!1,!1,!0);var b=this.F.V();if(g.KH(b)||g.UH(b)){var c={};b.Ma&&g.KH(b)&&g.bQ(c,b.loaderUrl);g.KH(b)&&g.lQ(this.F,"addEmbedsConversionTrackingParams",[c]);a:{switch(this.buttonType){case 2:b="emb_ytp_continue_watching";break a}b="emb_ytp_watch_again"}g.aQ(c,b);a=g.bi(a,c)}return a};
g.k.Va=function(){this.F.Va(this.element,this.tb&&this.Aa)};
g.k.show=function(){g.U.prototype.show.call(this);this.Va()};
g.k.hide=function(){g.U.prototype.hide.call(this);this.Va()};
g.k.kc=function(a){g.U.prototype.kc.call(this,a);this.Va()};g.v(L5,G5);L5.prototype.show=function(){3!==this.player.getPlayerState()&&(G5.prototype.show.call(this),this.j.qz(!0),this.j.Pq(!0),this.F.V().gm||this.j.Oq(!0),this.F.Va(this.element,!0),this.watchButton.kc(!0))};
L5.prototype.hide=function(){G5.prototype.hide.call(this);this.j.qz(!1);this.j.Pq(!1);this.j.Oq(!1);this.F.Va(this.element,!1);this.watchButton.kc(!1)};g.v(Ldb,G5);Ldb.prototype.La=function(){var a=this.player.getVideoData();this.j.update({profilePicture:a.profilePicture,author:a.author});this.subscribeButton.channelId=a.Zl;var b=this.subscribeButton;a.subscribed?b.j():b.u()};g.v(M5,g.U);M5.prototype.select=function(){this.api.Ln(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.YA||void 0)&&this.api.vb(this.element)};
M5.prototype.onClick=function(a){g.RR(a,this.api,this.u,this.suggestion.sessionData||void 0)&&this.select()};
M5.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.Dz(a)||(this.select(),g.Cz(a))}};
M5.prototype.onVideoDataChange=function(){var a=this.api.getVideoData(),b=this.api.V();this.u=a.D?!1:b.C};g.v(N5,G5);g.k=N5.prototype;g.k.create=function(){G5.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.videoData=a);this.Cp();this.u.S(this.player,"appresize",this.Cp);this.u.S(this.player,"onVideoAreaChange",this.Cp);this.u.S(this.player,"videodatachange",this.onVideoDataChange);this.u.S(this.player,"autonavchange",this.sI);this.u.S(this.player,"autonavcancel",this.aZ);a=this.videoData.autonavState;a!==this.T&&this.sI(a);this.u.S(this.element,"transitionend",this.F6)};
g.k.destroy=function(){g.JA(this.u);g.bb(this.stills);this.stills=[];G5.prototype.destroy.call(this);g.oo(this.element,"ytp-show-tiles");this.I.stop();this.T=this.videoData.autonavState};
g.k.DA=function(){return 1!==this.videoData.autonavState};
g.k.show=function(){var a=this.tb;G5.prototype.show.call(this);Mdb(this);g.oo(this.element,"ytp-show-tiles");this.player.V().u?g.go(this.I):this.I.start();(this.D||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.BQ(this.player,!1);O5(this)?(P5(this),2===this.videoData.autonavState?this.player.V().K("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.j.select(!0):this.j.zz():3===this.videoData.autonavState&&this.j.Hv()):(g.BQ(this.player,!0),P5(this));a!==this.tb&&this.player.Va(this.element,
!0)};
g.k.hide=function(){var a=this.tb;G5.prototype.hide.call(this);this.j.Hv();P5(this);a!==this.tb&&this.player.Va(this.element,!1)};
g.k.F6=function(a){g.yz(a)===this.element&&this.Cp()};
g.k.Cp=function(){var a=Mdb(this);if(a.length){g.mo(this.element,"ytp-endscreen-paginate");var b=this.F.zk(!0,this.F.isFullscreen()),c=g.oQ(this.F);c&&(c=c.vg()?48:32,b.width-=2*c);var d=b.width/b.height,e=96/54,f=c=2,h=Math.max(b.width/96,2),l=Math.max(b.height/54,2),m=a.length,n=Math.pow(2,2);var p=m*n+(Math.pow(2,2)-n);p+=Math.pow(2,2)-n;for(p-=n;0<p&&(c<h||f<l);){var q=c/2,r=f/2,w=c<=h-2&&p>=r*n,x=f<=l-2&&p>=q*n;if((q+1)/r*e/d>d/(q/(r+1)*e)&&x)p-=q*n,f+=2;else if(w)p-=r*n,c+=2;else if(x)p-=q*
n,f+=2;else break}e=!1;p>=3*n&&6>=m*n-p&&(4<=f||4<=c)&&(e=!0);n=96*c;p=54*f;d=n/p<d?b.height/p:b.width/n;d=Math.min(d,2);n=Math.floor(Math.min(b.width,n*d));p=Math.floor(Math.min(b.height,p*d));b=this.table.element;b.ariaLive="polite";g.Kl(b,n,p);g.ul(b,{marginLeft:n/-2+"px",marginTop:p/-2+"px"});this.j.VD(g.kJ(this.videoData));this.j instanceof E5&&F5(this.j);g.qo(this.element,"ytp-endscreen-takeover",O5(this));P5(this);n+=4;p+=4;d=0;b.ariaBusy="true";for(h=0;h<c;h++)for(l=0;l<f;l++)if(q=d,w=0,e&&
h>=c-2&&l>=f-2?w=1:0===l%2&&0===h%2&&(2>l&&2>h?0===l&&0===h&&(w=2):w=2),q=g.de(q+this.B,m),0!==w){r=this.stills[d];r||(r=new M5(this.player),this.stills[d]=r,b.appendChild(r.element));x=Math.floor(p*l/f);var z=Math.floor(n*h/c),B=Math.floor(p*(l+w)/f)-x-4,E=Math.floor(n*(h+w)/c)-z-4;g.Al(r.element,z,x);g.Kl(r.element,E,B);g.ul(r.element,"transitionDelay",(l+h)/20+"s");g.qo(r.element,"ytp-videowall-still-mini",1===w);g.qo(r.element,"ytp-videowall-still-large",2<w);this.Y&&(w=Math.max(E,B),g.qo(r.element,
"ytp-videowall-still-round-large",256<=w),g.qo(r.element,"ytp-videowall-still-round-medium",96<w&&256>w),g.qo(r.element,"ytp-videowall-still-round-small",96>=w));q=a[q];r.suggestion!==q&&(r.suggestion=q,w=r.api.V(),x=g.lo(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",C5(r,q,x),g.KH(w)&&(x=q.Jo(),z={},w.Ma&&g.bQ(z,w.loaderUrl),g.lQ(r.api,"addEmbedsConversionTrackingParams",[z]),x=g.bi(x,g.aQ(z,"emb_rel_end")),r.updateValue("url",x)),(q=(q=q.sessionData)&&q.itct)&&r.api.Kh(r.element,
q));d++}b.ariaBusy="false";g.qo(this.element,"ytp-endscreen-paginate",d<m);for(a=this.stills.length-1;a>=d;a--)c=this.stills[a],g.Pe(c.element),g.ab(c);this.stills.length=d}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.B=0,this.videoData=a,this.Cp())};
g.k.bZ=function(){this.B+=this.stills.length;this.Cp()};
g.k.cZ=function(){this.B-=this.stills.length;this.Cp()};
g.k.jU=function(){return this.j.Ek()};
g.k.sI=function(a){1===a?(this.D=!1,this.C=this.videoData.clientPlaybackNonce,this.j.Sq(),this.tb&&this.Cp()):(this.D=!0,this.tb&&O5(this)&&(2===a?this.j.zz():3===a&&this.j.Hv()))};
g.k.aZ=function(a){if(a){for(a=0;a<this.stills.length;a++)this.F.Va(this.stills[a].element,!0);this.sI(1)}else this.C=null,this.D=!1;this.Cp()};
g.k.Qf=function(){return this.tb&&O5(this)};g.v(Q5,G5);Q5.prototype.show=function(){if(3!==this.player.getPlayerState()){G5.prototype.show.call(this);var a=this.u;if(a){var b=0<this.j.suggestionData.length;g.qo(this.element,"ytp-shorts-branded-ui",b);b?a.show():a.hide()}var c;null==(c=g.oQ(this.player))||c.lD(!0);this.player.Va(this.element,!0);this.watchButton.kc(!0)}};
Q5.prototype.hide=function(){G5.prototype.hide.call(this);var a;null==(a=g.oQ(this.player))||a.lD(!1);this.player.Va(this.element,!1);this.watchButton.kc(!1)};g.v(Qdb,g.qR);g.k=Qdb.prototype;g.k.Yv=function(){var a;if((null==(a=g.oQ(this.player))?0:a.td())||this.u)return!0;a=this.player.getVideoData();var b;var c=!!((null==a?0:g.kJ(a))||(null==a?0:null==(b=a.suggestions)?0:b.length));b=!Ndb(this.player)||c;c=a.Qj||g.UH(a.u);var d=this.player.jB();a=a.mutedAutoplay;return b&&!c&&!d&&!a};
g.k.Qf=function(){return this.endScreen.Qf()};
g.k.f3=function(){return this.Qf()?this.endScreen.jU():!1};
g.k.qa=function(){this.player.Rf("endscreen");g.qR.prototype.qa.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.transitionEndpointAtEndOfStream;if(b&&b.videoId){var c=this.player.ub().gf.get("heartbeat"),d=g.kJ(a);!d||b.videoId!==d.videoId||a.VL?(this.player.Ln(b.videoId,void 0,void 0,!0,!0,b),c&&c.WF("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0):a=!1}else a=!1;a||(g.qR.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.qR.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.onCueRangeEnter=function(a){this.Yv()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.k.onCueRangeExit=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.k.onVideoDataChange=function(){Pdb(this);this.C&&Odb(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.j?this.endScreen=new I5(this.player):this.endScreen=new N5(this.player),g.D(this,this.endScreen),g.GQ(this.player,this.endScreen.element,4))};g.pR("endscreen",Qdb);})(_yt_player);
