(function(g){var window=this;'use strict';var Meb=function(a){g.U.call(this,{G:"div",N:"ytp-miniplayer-ui"});this.ag=!1;this.player=a;this.S(a,"minimized",this.Zh);this.S(a,"onStateChange",this.DO)},Neb=function(a){g.qR.call(this,a);
this.u=new g.MF(this);this.j=new Meb(this.player);this.j.hide();g.GQ(this.player,this.j.element,4);a.wg()&&(this.load(),g.qo(a.getRootNode(),"ytp-player-minimized",!0));this.player.K("web_rounded_containers")&&g.qo(a.getRootNode(),"ytp-rounded-miniplayer",!0)};
g.v(Meb,g.U);g.k=Meb.prototype;
g.k.FL=function(){this.tooltip=new g.xV(this.player,this);g.D(this,this.tooltip);g.GQ(this.player,this.tooltip.element,4);this.tooltip.scale=.6;this.Pc=new g.kS(this.player);g.D(this,this.Pc);this.sj=new g.U({G:"div",N:"ytp-miniplayer-scrim"});g.D(this,this.sj);this.sj.Da(this.element);this.S(this.sj.element,"click",this.wG);var a=new g.U({G:"button",Ja:["ytp-miniplayer-close-button","ytp-button"],X:{"aria-label":"Close"},W:[g.DN()]});g.D(this,a);a.Da(this.sj.element);this.S(a.element,"click",this.Yo);
a=new g.A2(this.player,this);g.D(this,a);a.Da(this.sj.element);this.Cu=new g.U({G:"div",N:"ytp-miniplayer-controls"});g.D(this,this.Cu);this.Cu.Da(this.sj.element);this.S(this.Cu.element,"click",this.wG);var b=new g.U({G:"div",N:"ytp-miniplayer-button-container"});g.D(this,b);b.Da(this.Cu.element);a=new g.U({G:"div",N:"ytp-miniplayer-play-button-container"});g.D(this,a);a.Da(this.Cu.element);var c=new g.U({G:"div",N:"ytp-miniplayer-button-container"});g.D(this,c);c.Da(this.Cu.element);this.bW=new g.RT(this.player,
this,!1);g.D(this,this.bW);this.bW.Da(b.element);b=new g.PT(this.player,this);g.D(this,b);b.Da(a.element);this.nextButton=new g.RT(this.player,this,!0);g.D(this,this.nextButton);this.nextButton.Da(c.element);this.uj=new g.kV(this.player,this);g.D(this,this.uj);this.uj.Da(this.sj.element);this.Ic=new g.cU(this.player,this);g.D(this,this.Ic);g.GQ(this.player,this.Ic.element,4);this.mG=new g.U({G:"div",N:"ytp-miniplayer-buttons"});g.D(this,this.mG);g.GQ(this.player,this.mG.element,4);a=new g.U({G:"button",
Ja:["ytp-miniplayer-close-button","ytp-button"],X:{"aria-label":"Close"},W:[g.DN()]});g.D(this,a);a.Da(this.mG.element);this.S(a.element,"click",this.Yo);a=new g.U({G:"button",Ja:["ytp-miniplayer-replay-button","ytp-button"],X:{"aria-label":"Close"},W:[g.KN()]});g.D(this,a);a.Da(this.mG.element);this.S(a.element,"click",this.T5);this.S(this.player,"presentingplayerstatechange",this.yd);this.S(this.player,"appresize",this.Eb);this.S(this.player,"fullscreentoggled",this.Eb);this.Eb()};
g.k.show=function(){this.qf=new g.bo(this.Av,null,this);this.qf.start();this.ag||(this.FL(),this.ag=!0);0!==this.player.getPlayerState()&&g.U.prototype.show.call(this);this.Ic.show();this.player.unloadModule("annotations_module")};
g.k.hide=function(){this.qf&&(this.qf.dispose(),this.qf=void 0);g.U.prototype.hide.call(this);this.player.wg()||(this.ag&&this.Ic.hide(),this.player.loadModule("annotations_module"))};
g.k.qa=function(){this.qf&&(this.qf.dispose(),this.qf=void 0);g.U.prototype.qa.call(this)};
g.k.Yo=function(){this.player.stopVideo();this.player.Na("onCloseMiniplayer")};
g.k.T5=function(){this.player.playVideo()};
g.k.wG=function(a){if(a.target===this.sj.element||a.target===this.Cu.element)g.mM(this.player.Gb())?this.player.pauseVideo():this.player.playVideo()};
g.k.Zh=function(){g.qo(this.player.getRootNode(),"ytp-player-minimized",this.player.wg())};
g.k.Oe=function(){this.Ic.xc();this.uj.xc()};
g.k.Av=function(){this.Oe();this.qf&&this.qf.start()};
g.k.yd=function(a){g.T(a.state,32)&&this.tooltip.hide()};
g.k.Eb=function(){g.vU(this.Ic,0,this.player.ib().getPlayerSize().width,!1);g.fU(this.Ic)};
g.k.DO=function(a){this.player.wg()&&(0===a?this.hide():this.show())};
g.k.Ac=function(){return this.tooltip};
g.k.vg=function(){return!1};
g.k.lh=function(){return!1};
g.k.td=function(){return!1};
g.k.Ll=function(){return!1};
g.k.kD=function(){};
g.k.Op=function(){};
g.k.Px=function(){};
g.k.Lm=function(){return null};
g.k.iF=function(){return null};
g.k.AB=function(){return null};
g.k.zk=function(){return new g.rl(0,0,0,0)};
g.k.handleGlobalKeyDown=function(){return!1};
g.k.handleGlobalKeyUp=function(){return!1};
g.k.Lv=function(a,b,c,d,e){var f=0,h=d=0,l=g.Ll(a);if(b){c=g.lo(b,"ytp-prev-button")||g.lo(b,"ytp-next-button");var m=g.lo(b,"ytp-play-button"),n=g.lo(b,"ytp-miniplayer-expand-watch-page-button");c?f=h=12:m?(b=g.Jl(b,this.element),h=b.x,f=b.y-12):n&&(h=g.lo(b,"ytp-miniplayer-button-top-left"),f=g.Jl(b,this.element),b=g.Ll(b),h?(h=8,f=f.y+40):(h=f.x-l.width+b.width,f=f.y-20))}else h=c-l.width/2,d=25+(e||0);b=this.player.ib().getPlayerSize().width;e=f+(e||0);l=g.ce(h,0,b-l.width);e?(a.style.top=e+"px",
a.style.bottom=""):(a.style.top="",a.style.bottom=d+"px");a.style.left=l+"px"};
g.k.showControls=function(){};
g.k.qp=function(){};
g.k.Gl=function(){return!1};
g.k.lD=function(){};
g.k.qz=function(){};
g.k.Pq=function(){};
g.k.Oq=function(){};
g.k.rE=function(){};
g.k.Nr=function(){};g.v(Neb,g.qR);g.k=Neb.prototype;g.k.onVideoDataChange=function(){if(this.player.K("web_rounded_containers")&&this.player.getVideoData()){var a=this.player.getVideoAspectRatio(),b=16/9,c=a>b+.1;g.Uv("enable_no_border_vertical_videos_killswitch")?g.qo(this.player.getRootNode(),"ytp-rounded-miniplayer-not-regular-wide-video",c):(a=c||a<b-.1,g.qo(this.player.getRootNode(),"ytp-rounded-miniplayer-not-regular-wide-video",a))}};
g.k.create=function(){g.qR.prototype.create.call(this);this.u.S(this.player,"videodatachange",this.onVideoDataChange);this.onVideoDataChange()};
g.k.Qk=function(){return!1};
g.k.load=function(){this.player.hideControls();this.j.show()};
g.k.unload=function(){this.player.showControls();this.j.hide()};g.pR("miniplayer",Neb);})(_yt_player);
